# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/aes_gcm_siv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/aes_gcm_siv.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z1github.com/google/tink/proto/aes_gcm_siv_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ctink/proto/aes_gcm_siv.proto\x12\x12google.crypto.tink\"7\n\x12\x41\x65sGcmSivKeyFormat\x12\x10\n\x08key_size\x18\x02 \x01(\r\x12\x0f\n\x07version\x18\x01 \x01(\r\"2\n\x0c\x41\x65sGcmSivKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tkey_value\x18\x03 \x01(\x0c\x42S\n\x1c\x63om.google.crypto.tink.protoP\x01Z1github.com/google/tink/proto/aes_gcm_siv_go_protob\x06proto3'
)




_AESGCMSIVKEYFORMAT = _descriptor.Descriptor(
  name='AesGcmSivKeyFormat',
  full_name='google.crypto.tink.AesGcmSivKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_size', full_name='google.crypto.tink.AesGcmSivKeyFormat.key_size', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesGcmSivKeyFormat.version', index=1,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=107,
)


_AESGCMSIVKEY = _descriptor.Descriptor(
  name='AesGcmSivKey',
  full_name='google.crypto.tink.AesGcmSivKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesGcmSivKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.AesGcmSivKey.key_value', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['AesGcmSivKeyFormat'] = _AESGCMSIVKEYFORMAT
DESCRIPTOR.message_types_by_name['AesGcmSivKey'] = _AESGCMSIVKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AesGcmSivKeyFormat = _reflection.GeneratedProtocolMessageType('AesGcmSivKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _AESGCMSIVKEYFORMAT,
  '__module__' : 'tink.proto.aes_gcm_siv_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesGcmSivKeyFormat)
  })
_sym_db.RegisterMessage(AesGcmSivKeyFormat)

AesGcmSivKey = _reflection.GeneratedProtocolMessageType('AesGcmSivKey', (_message.Message,), {
  'DESCRIPTOR' : _AESGCMSIVKEY,
  '__module__' : 'tink.proto.aes_gcm_siv_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesGcmSivKey)
  })
_sym_db.RegisterMessage(AesGcmSivKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
