# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/aes_ctr_hmac_aead.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import aes_ctr_pb2 as tink_dot_proto_dot_aes__ctr__pb2
from tink.proto import hmac_pb2 as tink_dot_proto_dot_hmac__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/aes_ctr_hmac_aead.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z7github.com/google/tink/proto/aes_ctr_hmac_aead_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"tink/proto/aes_ctr_hmac_aead.proto\x12\x12google.crypto.tink\x1a\x18tink/proto/aes_ctr.proto\x1a\x15tink/proto/hmac.proto\"\x96\x01\n\x17\x41\x65sCtrHmacAeadKeyFormat\x12?\n\x12\x61\x65s_ctr_key_format\x18\x01 \x01(\x0b\x32#.google.crypto.tink.AesCtrKeyFormat\x12:\n\x0fhmac_key_format\x18\x02 \x01(\x0b\x32!.google.crypto.tink.HmacKeyFormat\"\x87\x01\n\x11\x41\x65sCtrHmacAeadKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x32\n\x0b\x61\x65s_ctr_key\x18\x02 \x01(\x0b\x32\x1d.google.crypto.tink.AesCtrKey\x12-\n\x08hmac_key\x18\x03 \x01(\x0b\x32\x1b.google.crypto.tink.HmacKeyBY\n\x1c\x63om.google.crypto.tink.protoP\x01Z7github.com/google/tink/proto/aes_ctr_hmac_aead_go_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_aes__ctr__pb2.DESCRIPTOR,tink_dot_proto_dot_hmac__pb2.DESCRIPTOR,])




_AESCTRHMACAEADKEYFORMAT = _descriptor.Descriptor(
  name='AesCtrHmacAeadKeyFormat',
  full_name='google.crypto.tink.AesCtrHmacAeadKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='aes_ctr_key_format', full_name='google.crypto.tink.AesCtrHmacAeadKeyFormat.aes_ctr_key_format', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hmac_key_format', full_name='google.crypto.tink.AesCtrHmacAeadKeyFormat.hmac_key_format', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=258,
)


_AESCTRHMACAEADKEY = _descriptor.Descriptor(
  name='AesCtrHmacAeadKey',
  full_name='google.crypto.tink.AesCtrHmacAeadKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesCtrHmacAeadKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aes_ctr_key', full_name='google.crypto.tink.AesCtrHmacAeadKey.aes_ctr_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hmac_key', full_name='google.crypto.tink.AesCtrHmacAeadKey.hmac_key', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=396,
)

_AESCTRHMACAEADKEYFORMAT.fields_by_name['aes_ctr_key_format'].message_type = tink_dot_proto_dot_aes__ctr__pb2._AESCTRKEYFORMAT
_AESCTRHMACAEADKEYFORMAT.fields_by_name['hmac_key_format'].message_type = tink_dot_proto_dot_hmac__pb2._HMACKEYFORMAT
_AESCTRHMACAEADKEY.fields_by_name['aes_ctr_key'].message_type = tink_dot_proto_dot_aes__ctr__pb2._AESCTRKEY
_AESCTRHMACAEADKEY.fields_by_name['hmac_key'].message_type = tink_dot_proto_dot_hmac__pb2._HMACKEY
DESCRIPTOR.message_types_by_name['AesCtrHmacAeadKeyFormat'] = _AESCTRHMACAEADKEYFORMAT
DESCRIPTOR.message_types_by_name['AesCtrHmacAeadKey'] = _AESCTRHMACAEADKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AesCtrHmacAeadKeyFormat = _reflection.GeneratedProtocolMessageType('AesCtrHmacAeadKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _AESCTRHMACAEADKEYFORMAT,
  '__module__' : 'tink.proto.aes_ctr_hmac_aead_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesCtrHmacAeadKeyFormat)
  })
_sym_db.RegisterMessage(AesCtrHmacAeadKeyFormat)

AesCtrHmacAeadKey = _reflection.GeneratedProtocolMessageType('AesCtrHmacAeadKey', (_message.Message,), {
  'DESCRIPTOR' : _AESCTRHMACAEADKEY,
  '__module__' : 'tink.proto.aes_ctr_hmac_aead_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesCtrHmacAeadKey)
  })
_sym_db.RegisterMessage(AesCtrHmacAeadKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
