# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/aes_ctr_hmac_streaming.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import common_pb2 as tink_dot_proto_dot_common__pb2
from tink.proto import hmac_pb2 as tink_dot_proto_dot_hmac__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/aes_ctr_hmac_streaming.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z<github.com/google/tink/proto/aes_ctr_hmac_streaming_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'tink/proto/aes_ctr_hmac_streaming.proto\x12\x12google.crypto.tink\x1a\x17tink/proto/common.proto\x1a\x15tink/proto/hmac.proto\"\xc1\x01\n\x19\x41\x65sCtrHmacStreamingParams\x12\x1f\n\x17\x63iphertext_segment_size\x18\x01 \x01(\r\x12\x18\n\x10\x64\x65rived_key_size\x18\x02 \x01(\r\x12\x34\n\x0ehkdf_hash_type\x18\x03 \x01(\x0e\x32\x1c.google.crypto.tink.HashType\x12\x33\n\x0bhmac_params\x18\x04 \x01(\x0b\x32\x1e.google.crypto.tink.HmacParams\"\x80\x01\n\x1c\x41\x65sCtrHmacStreamingKeyFormat\x12\x0f\n\x07version\x18\x03 \x01(\r\x12=\n\x06params\x18\x01 \x01(\x0b\x32-.google.crypto.tink.AesCtrHmacStreamingParams\x12\x10\n\x08key_size\x18\x02 \x01(\r\"{\n\x16\x41\x65sCtrHmacStreamingKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12=\n\x06params\x18\x02 \x01(\x0b\x32-.google.crypto.tink.AesCtrHmacStreamingParams\x12\x11\n\tkey_value\x18\x03 \x01(\x0c\x42^\n\x1c\x63om.google.crypto.tink.protoP\x01Z<github.com/google/tink/proto/aes_ctr_hmac_streaming_go_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_common__pb2.DESCRIPTOR,tink_dot_proto_dot_hmac__pb2.DESCRIPTOR,])




_AESCTRHMACSTREAMINGPARAMS = _descriptor.Descriptor(
  name='AesCtrHmacStreamingParams',
  full_name='google.crypto.tink.AesCtrHmacStreamingParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ciphertext_segment_size', full_name='google.crypto.tink.AesCtrHmacStreamingParams.ciphertext_segment_size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='derived_key_size', full_name='google.crypto.tink.AesCtrHmacStreamingParams.derived_key_size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hkdf_hash_type', full_name='google.crypto.tink.AesCtrHmacStreamingParams.hkdf_hash_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hmac_params', full_name='google.crypto.tink.AesCtrHmacStreamingParams.hmac_params', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=305,
)


_AESCTRHMACSTREAMINGKEYFORMAT = _descriptor.Descriptor(
  name='AesCtrHmacStreamingKeyFormat',
  full_name='google.crypto.tink.AesCtrHmacStreamingKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesCtrHmacStreamingKeyFormat.version', index=0,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.AesCtrHmacStreamingKeyFormat.params', index=1,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_size', full_name='google.crypto.tink.AesCtrHmacStreamingKeyFormat.key_size', index=2,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=436,
)


_AESCTRHMACSTREAMINGKEY = _descriptor.Descriptor(
  name='AesCtrHmacStreamingKey',
  full_name='google.crypto.tink.AesCtrHmacStreamingKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesCtrHmacStreamingKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.AesCtrHmacStreamingKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.AesCtrHmacStreamingKey.key_value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=561,
)

_AESCTRHMACSTREAMINGPARAMS.fields_by_name['hkdf_hash_type'].enum_type = tink_dot_proto_dot_common__pb2._HASHTYPE
_AESCTRHMACSTREAMINGPARAMS.fields_by_name['hmac_params'].message_type = tink_dot_proto_dot_hmac__pb2._HMACPARAMS
_AESCTRHMACSTREAMINGKEYFORMAT.fields_by_name['params'].message_type = _AESCTRHMACSTREAMINGPARAMS
_AESCTRHMACSTREAMINGKEY.fields_by_name['params'].message_type = _AESCTRHMACSTREAMINGPARAMS
DESCRIPTOR.message_types_by_name['AesCtrHmacStreamingParams'] = _AESCTRHMACSTREAMINGPARAMS
DESCRIPTOR.message_types_by_name['AesCtrHmacStreamingKeyFormat'] = _AESCTRHMACSTREAMINGKEYFORMAT
DESCRIPTOR.message_types_by_name['AesCtrHmacStreamingKey'] = _AESCTRHMACSTREAMINGKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AesCtrHmacStreamingParams = _reflection.GeneratedProtocolMessageType('AesCtrHmacStreamingParams', (_message.Message,), {
  'DESCRIPTOR' : _AESCTRHMACSTREAMINGPARAMS,
  '__module__' : 'tink.proto.aes_ctr_hmac_streaming_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesCtrHmacStreamingParams)
  })
_sym_db.RegisterMessage(AesCtrHmacStreamingParams)

AesCtrHmacStreamingKeyFormat = _reflection.GeneratedProtocolMessageType('AesCtrHmacStreamingKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _AESCTRHMACSTREAMINGKEYFORMAT,
  '__module__' : 'tink.proto.aes_ctr_hmac_streaming_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesCtrHmacStreamingKeyFormat)
  })
_sym_db.RegisterMessage(AesCtrHmacStreamingKeyFormat)

AesCtrHmacStreamingKey = _reflection.GeneratedProtocolMessageType('AesCtrHmacStreamingKey', (_message.Message,), {
  'DESCRIPTOR' : _AESCTRHMACSTREAMINGKEY,
  '__module__' : 'tink.proto.aes_ctr_hmac_streaming_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesCtrHmacStreamingKey)
  })
_sym_db.RegisterMessage(AesCtrHmacStreamingKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
