# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/aes_gcm_hkdf_streaming.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import common_pb2 as tink_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/aes_gcm_hkdf_streaming.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z<github.com/google/tink/proto/aes_gcm_hkdf_streaming_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'tink/proto/aes_gcm_hkdf_streaming.proto\x12\x12google.crypto.tink\x1a\x17tink/proto/common.proto\"\x8c\x01\n\x19\x41\x65sGcmHkdfStreamingParams\x12\x1f\n\x17\x63iphertext_segment_size\x18\x01 \x01(\r\x12\x18\n\x10\x64\x65rived_key_size\x18\x02 \x01(\r\x12\x34\n\x0ehkdf_hash_type\x18\x03 \x01(\x0e\x32\x1c.google.crypto.tink.HashType\"\x80\x01\n\x1c\x41\x65sGcmHkdfStreamingKeyFormat\x12\x0f\n\x07version\x18\x03 \x01(\r\x12=\n\x06params\x18\x01 \x01(\x0b\x32-.google.crypto.tink.AesGcmHkdfStreamingParams\x12\x10\n\x08key_size\x18\x02 \x01(\r\"{\n\x16\x41\x65sGcmHkdfStreamingKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12=\n\x06params\x18\x02 \x01(\x0b\x32-.google.crypto.tink.AesGcmHkdfStreamingParams\x12\x11\n\tkey_value\x18\x03 \x01(\x0c\x42^\n\x1c\x63om.google.crypto.tink.protoP\x01Z<github.com/google/tink/proto/aes_gcm_hkdf_streaming_go_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_common__pb2.DESCRIPTOR,])




_AESGCMHKDFSTREAMINGPARAMS = _descriptor.Descriptor(
  name='AesGcmHkdfStreamingParams',
  full_name='google.crypto.tink.AesGcmHkdfStreamingParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ciphertext_segment_size', full_name='google.crypto.tink.AesGcmHkdfStreamingParams.ciphertext_segment_size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='derived_key_size', full_name='google.crypto.tink.AesGcmHkdfStreamingParams.derived_key_size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hkdf_hash_type', full_name='google.crypto.tink.AesGcmHkdfStreamingParams.hkdf_hash_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=229,
)


_AESGCMHKDFSTREAMINGKEYFORMAT = _descriptor.Descriptor(
  name='AesGcmHkdfStreamingKeyFormat',
  full_name='google.crypto.tink.AesGcmHkdfStreamingKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesGcmHkdfStreamingKeyFormat.version', index=0,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.AesGcmHkdfStreamingKeyFormat.params', index=1,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_size', full_name='google.crypto.tink.AesGcmHkdfStreamingKeyFormat.key_size', index=2,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=360,
)


_AESGCMHKDFSTREAMINGKEY = _descriptor.Descriptor(
  name='AesGcmHkdfStreamingKey',
  full_name='google.crypto.tink.AesGcmHkdfStreamingKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesGcmHkdfStreamingKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.AesGcmHkdfStreamingKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.AesGcmHkdfStreamingKey.key_value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=485,
)

_AESGCMHKDFSTREAMINGPARAMS.fields_by_name['hkdf_hash_type'].enum_type = tink_dot_proto_dot_common__pb2._HASHTYPE
_AESGCMHKDFSTREAMINGKEYFORMAT.fields_by_name['params'].message_type = _AESGCMHKDFSTREAMINGPARAMS
_AESGCMHKDFSTREAMINGKEY.fields_by_name['params'].message_type = _AESGCMHKDFSTREAMINGPARAMS
DESCRIPTOR.message_types_by_name['AesGcmHkdfStreamingParams'] = _AESGCMHKDFSTREAMINGPARAMS
DESCRIPTOR.message_types_by_name['AesGcmHkdfStreamingKeyFormat'] = _AESGCMHKDFSTREAMINGKEYFORMAT
DESCRIPTOR.message_types_by_name['AesGcmHkdfStreamingKey'] = _AESGCMHKDFSTREAMINGKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AesGcmHkdfStreamingParams = _reflection.GeneratedProtocolMessageType('AesGcmHkdfStreamingParams', (_message.Message,), {
  'DESCRIPTOR' : _AESGCMHKDFSTREAMINGPARAMS,
  '__module__' : 'tink.proto.aes_gcm_hkdf_streaming_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesGcmHkdfStreamingParams)
  })
_sym_db.RegisterMessage(AesGcmHkdfStreamingParams)

AesGcmHkdfStreamingKeyFormat = _reflection.GeneratedProtocolMessageType('AesGcmHkdfStreamingKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _AESGCMHKDFSTREAMINGKEYFORMAT,
  '__module__' : 'tink.proto.aes_gcm_hkdf_streaming_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesGcmHkdfStreamingKeyFormat)
  })
_sym_db.RegisterMessage(AesGcmHkdfStreamingKeyFormat)

AesGcmHkdfStreamingKey = _reflection.GeneratedProtocolMessageType('AesGcmHkdfStreamingKey', (_message.Message,), {
  'DESCRIPTOR' : _AESGCMHKDFSTREAMINGKEY,
  '__module__' : 'tink.proto.aes_gcm_hkdf_streaming_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesGcmHkdfStreamingKey)
  })
_sym_db.RegisterMessage(AesGcmHkdfStreamingKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
