# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/aes_cmac.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/aes_cmac.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z.github.com/google/tink/proto/aes_cmac_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19tink/proto/aes_cmac.proto\x12\x12google.crypto.tink\"!\n\rAesCmacParams\x12\x10\n\x08tag_size\x18\x01 \x01(\r\"c\n\nAesCmacKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tkey_value\x18\x02 \x01(\x0c\x12\x31\n\x06params\x18\x03 \x01(\x0b\x32!.google.crypto.tink.AesCmacParams\"W\n\x10\x41\x65sCmacKeyFormat\x12\x10\n\x08key_size\x18\x01 \x01(\r\x12\x31\n\x06params\x18\x02 \x01(\x0b\x32!.google.crypto.tink.AesCmacParamsBP\n\x1c\x63om.google.crypto.tink.protoP\x01Z.github.com/google/tink/proto/aes_cmac_go_protob\x06proto3'
)




_AESCMACPARAMS = _descriptor.Descriptor(
  name='AesCmacParams',
  full_name='google.crypto.tink.AesCmacParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag_size', full_name='google.crypto.tink.AesCmacParams.tag_size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=82,
)


_AESCMACKEY = _descriptor.Descriptor(
  name='AesCmacKey',
  full_name='google.crypto.tink.AesCmacKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesCmacKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.AesCmacKey.key_value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.AesCmacKey.params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=183,
)


_AESCMACKEYFORMAT = _descriptor.Descriptor(
  name='AesCmacKeyFormat',
  full_name='google.crypto.tink.AesCmacKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_size', full_name='google.crypto.tink.AesCmacKeyFormat.key_size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.AesCmacKeyFormat.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=272,
)

_AESCMACKEY.fields_by_name['params'].message_type = _AESCMACPARAMS
_AESCMACKEYFORMAT.fields_by_name['params'].message_type = _AESCMACPARAMS
DESCRIPTOR.message_types_by_name['AesCmacParams'] = _AESCMACPARAMS
DESCRIPTOR.message_types_by_name['AesCmacKey'] = _AESCMACKEY
DESCRIPTOR.message_types_by_name['AesCmacKeyFormat'] = _AESCMACKEYFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AesCmacParams = _reflection.GeneratedProtocolMessageType('AesCmacParams', (_message.Message,), {
  'DESCRIPTOR' : _AESCMACPARAMS,
  '__module__' : 'tink.proto.aes_cmac_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesCmacParams)
  })
_sym_db.RegisterMessage(AesCmacParams)

AesCmacKey = _reflection.GeneratedProtocolMessageType('AesCmacKey', (_message.Message,), {
  'DESCRIPTOR' : _AESCMACKEY,
  '__module__' : 'tink.proto.aes_cmac_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesCmacKey)
  })
_sym_db.RegisterMessage(AesCmacKey)

AesCmacKeyFormat = _reflection.GeneratedProtocolMessageType('AesCmacKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _AESCMACKEYFORMAT,
  '__module__' : 'tink.proto.aes_cmac_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesCmacKeyFormat)
  })
_sym_db.RegisterMessage(AesCmacKeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
