# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/aes_gcm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/aes_gcm.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z-github.com/google/tink/proto/aes_gcm_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18tink/proto/aes_gcm.proto\x12\x12google.crypto.tink\"4\n\x0f\x41\x65sGcmKeyFormat\x12\x10\n\x08key_size\x18\x02 \x01(\r\x12\x0f\n\x07version\x18\x03 \x01(\r\"/\n\tAesGcmKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tkey_value\x18\x03 \x01(\x0c\x42O\n\x1c\x63om.google.crypto.tink.protoP\x01Z-github.com/google/tink/proto/aes_gcm_go_protob\x06proto3'
)




_AESGCMKEYFORMAT = _descriptor.Descriptor(
  name='AesGcmKeyFormat',
  full_name='google.crypto.tink.AesGcmKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_size', full_name='google.crypto.tink.AesGcmKeyFormat.key_size', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesGcmKeyFormat.version', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=100,
)


_AESGCMKEY = _descriptor.Descriptor(
  name='AesGcmKey',
  full_name='google.crypto.tink.AesGcmKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesGcmKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.AesGcmKey.key_value', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['AesGcmKeyFormat'] = _AESGCMKEYFORMAT
DESCRIPTOR.message_types_by_name['AesGcmKey'] = _AESGCMKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AesGcmKeyFormat = _reflection.GeneratedProtocolMessageType('AesGcmKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _AESGCMKEYFORMAT,
  '__module__' : 'tink.proto.aes_gcm_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesGcmKeyFormat)
  })
_sym_db.RegisterMessage(AesGcmKeyFormat)

AesGcmKey = _reflection.GeneratedProtocolMessageType('AesGcmKey', (_message.Message,), {
  'DESCRIPTOR' : _AESGCMKEY,
  '__module__' : 'tink.proto.aes_gcm_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesGcmKey)
  })
_sym_db.RegisterMessage(AesGcmKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
