# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/aes_cmac_prf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/aes_cmac_prf.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z2github.com/google/tink/proto/aes_cmac_prf_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dtink/proto/aes_cmac_prf.proto\x12\x12google.crypto.tink\"3\n\rAesCmacPrfKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tkey_value\x18\x02 \x01(\x0c\"8\n\x13\x41\x65sCmacPrfKeyFormat\x12\x0f\n\x07version\x18\x02 \x01(\r\x12\x10\n\x08key_size\x18\x01 \x01(\rBT\n\x1c\x63om.google.crypto.tink.protoP\x01Z2github.com/google/tink/proto/aes_cmac_prf_go_protob\x06proto3'
)




_AESCMACPRFKEY = _descriptor.Descriptor(
  name='AesCmacPrfKey',
  full_name='google.crypto.tink.AesCmacPrfKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesCmacPrfKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.AesCmacPrfKey.key_value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=104,
)


_AESCMACPRFKEYFORMAT = _descriptor.Descriptor(
  name='AesCmacPrfKeyFormat',
  full_name='google.crypto.tink.AesCmacPrfKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesCmacPrfKeyFormat.version', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_size', full_name='google.crypto.tink.AesCmacPrfKeyFormat.key_size', index=1,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['AesCmacPrfKey'] = _AESCMACPRFKEY
DESCRIPTOR.message_types_by_name['AesCmacPrfKeyFormat'] = _AESCMACPRFKEYFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AesCmacPrfKey = _reflection.GeneratedProtocolMessageType('AesCmacPrfKey', (_message.Message,), {
  'DESCRIPTOR' : _AESCMACPRFKEY,
  '__module__' : 'tink.proto.aes_cmac_prf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesCmacPrfKey)
  })
_sym_db.RegisterMessage(AesCmacPrfKey)

AesCmacPrfKeyFormat = _reflection.GeneratedProtocolMessageType('AesCmacPrfKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _AESCMACPRFKEYFORMAT,
  '__module__' : 'tink.proto.aes_cmac_prf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesCmacPrfKeyFormat)
  })
_sym_db.RegisterMessage(AesCmacPrfKeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
