# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/aes_siv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/aes_siv.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z-github.com/google/tink/proto/aes_siv_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18tink/proto/aes_siv.proto\x12\x12google.crypto.tink\"4\n\x0f\x41\x65sSivKeyFormat\x12\x10\n\x08key_size\x18\x01 \x01(\r\x12\x0f\n\x07version\x18\x02 \x01(\r\"/\n\tAesSivKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tkey_value\x18\x02 \x01(\x0c\x42O\n\x1c\x63om.google.crypto.tink.protoP\x01Z-github.com/google/tink/proto/aes_siv_go_protob\x06proto3'
)




_AESSIVKEYFORMAT = _descriptor.Descriptor(
  name='AesSivKeyFormat',
  full_name='google.crypto.tink.AesSivKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_size', full_name='google.crypto.tink.AesSivKeyFormat.key_size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesSivKeyFormat.version', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=100,
)


_AESSIVKEY = _descriptor.Descriptor(
  name='AesSivKey',
  full_name='google.crypto.tink.AesSivKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.AesSivKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.AesSivKey.key_value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['AesSivKeyFormat'] = _AESSIVKEYFORMAT
DESCRIPTOR.message_types_by_name['AesSivKey'] = _AESSIVKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AesSivKeyFormat = _reflection.GeneratedProtocolMessageType('AesSivKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _AESSIVKEYFORMAT,
  '__module__' : 'tink.proto.aes_siv_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesSivKeyFormat)
  })
_sym_db.RegisterMessage(AesSivKeyFormat)

AesSivKey = _reflection.GeneratedProtocolMessageType('AesSivKey', (_message.Message,), {
  'DESCRIPTOR' : _AESSIVKEY,
  '__module__' : 'tink.proto.aes_siv_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.AesSivKey)
  })
_sym_db.RegisterMessage(AesSivKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
