# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/cached_dek_envelope.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import tink_pb2 as tink_dot_proto_dot_tink__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/cached_dek_envelope.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z9github.com/google/tink/proto/cached_dek_envelope_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$tink/proto/cached_dek_envelope.proto\x12\x12google.crypto.tink\x1a\x15tink/proto/tink.proto\"h\n\x1e\x43\x61\x63hedDekEnvelopeAeadKeyFormat\x12\x0f\n\x07kek_uri\x18\x01 \x01(\t\x12\x35\n\x0c\x64\x65k_template\x18\x02 \x01(\x0b\x32\x1f.google.crypto.tink.KeyTemplate\"o\n\x18\x43\x61\x63hedDekEnvelopeAeadKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x42\n\x06params\x18\x02 \x01(\x0b\x32\x32.google.crypto.tink.CachedDekEnvelopeAeadKeyFormatB[\n\x1c\x63om.google.crypto.tink.protoP\x01Z9github.com/google/tink/proto/cached_dek_envelope_go_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_tink__pb2.DESCRIPTOR,])




_CACHEDDEKENVELOPEAEADKEYFORMAT = _descriptor.Descriptor(
  name='CachedDekEnvelopeAeadKeyFormat',
  full_name='google.crypto.tink.CachedDekEnvelopeAeadKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kek_uri', full_name='google.crypto.tink.CachedDekEnvelopeAeadKeyFormat.kek_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dek_template', full_name='google.crypto.tink.CachedDekEnvelopeAeadKeyFormat.dek_template', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=187,
)


_CACHEDDEKENVELOPEAEADKEY = _descriptor.Descriptor(
  name='CachedDekEnvelopeAeadKey',
  full_name='google.crypto.tink.CachedDekEnvelopeAeadKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.CachedDekEnvelopeAeadKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.CachedDekEnvelopeAeadKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=300,
)

_CACHEDDEKENVELOPEAEADKEYFORMAT.fields_by_name['dek_template'].message_type = tink_dot_proto_dot_tink__pb2._KEYTEMPLATE
_CACHEDDEKENVELOPEAEADKEY.fields_by_name['params'].message_type = _CACHEDDEKENVELOPEAEADKEYFORMAT
DESCRIPTOR.message_types_by_name['CachedDekEnvelopeAeadKeyFormat'] = _CACHEDDEKENVELOPEAEADKEYFORMAT
DESCRIPTOR.message_types_by_name['CachedDekEnvelopeAeadKey'] = _CACHEDDEKENVELOPEAEADKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CachedDekEnvelopeAeadKeyFormat = _reflection.GeneratedProtocolMessageType('CachedDekEnvelopeAeadKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _CACHEDDEKENVELOPEAEADKEYFORMAT,
  '__module__' : 'tink.proto.cached_dek_envelope_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.CachedDekEnvelopeAeadKeyFormat)
  })
_sym_db.RegisterMessage(CachedDekEnvelopeAeadKeyFormat)

CachedDekEnvelopeAeadKey = _reflection.GeneratedProtocolMessageType('CachedDekEnvelopeAeadKey', (_message.Message,), {
  'DESCRIPTOR' : _CACHEDDEKENVELOPEAEADKEY,
  '__module__' : 'tink.proto.cached_dek_envelope_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.CachedDekEnvelopeAeadKey)
  })
_sym_db.RegisterMessage(CachedDekEnvelopeAeadKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
