# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/common.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z,github.com/google/tink/proto/common_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17tink/proto/common.proto\x12\x12google.crypto.tink*c\n\x11\x45llipticCurveType\x12\x11\n\rUNKNOWN_CURVE\x10\x00\x12\r\n\tNIST_P256\x10\x02\x12\r\n\tNIST_P384\x10\x03\x12\r\n\tNIST_P521\x10\x04\x12\x0e\n\nCURVE25519\x10\x05*j\n\rEcPointFormat\x12\x12\n\x0eUNKNOWN_FORMAT\x10\x00\x12\x10\n\x0cUNCOMPRESSED\x10\x01\x12\x0e\n\nCOMPRESSED\x10\x02\x12#\n\x1f\x44O_NOT_USE_CRUNCHY_UNCOMPRESSED\x10\x03*V\n\x08HashType\x12\x10\n\x0cUNKNOWN_HASH\x10\x00\x12\x08\n\x04SHA1\x10\x01\x12\n\n\x06SHA384\x10\x02\x12\n\n\x06SHA256\x10\x03\x12\n\n\x06SHA512\x10\x04\x12\n\n\x06SHA224\x10\x05\x42N\n\x1c\x63om.google.crypto.tink.protoP\x01Z,github.com/google/tink/proto/common_go_protob\x06proto3'
)

_ELLIPTICCURVETYPE = _descriptor.EnumDescriptor(
  name='EllipticCurveType',
  full_name='google.crypto.tink.EllipticCurveType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_CURVE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NIST_P256', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NIST_P384', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NIST_P521', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CURVE25519', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=47,
  serialized_end=146,
)
_sym_db.RegisterEnumDescriptor(_ELLIPTICCURVETYPE)

EllipticCurveType = enum_type_wrapper.EnumTypeWrapper(_ELLIPTICCURVETYPE)
_ECPOINTFORMAT = _descriptor.EnumDescriptor(
  name='EcPointFormat',
  full_name='google.crypto.tink.EcPointFormat',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_FORMAT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNCOMPRESSED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMPRESSED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DO_NOT_USE_CRUNCHY_UNCOMPRESSED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=148,
  serialized_end=254,
)
_sym_db.RegisterEnumDescriptor(_ECPOINTFORMAT)

EcPointFormat = enum_type_wrapper.EnumTypeWrapper(_ECPOINTFORMAT)
_HASHTYPE = _descriptor.EnumDescriptor(
  name='HashType',
  full_name='google.crypto.tink.HashType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_HASH', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHA1', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHA384', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHA256', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHA512', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHA224', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=256,
  serialized_end=342,
)
_sym_db.RegisterEnumDescriptor(_HASHTYPE)

HashType = enum_type_wrapper.EnumTypeWrapper(_HASHTYPE)
UNKNOWN_CURVE = 0
NIST_P256 = 2
NIST_P384 = 3
NIST_P521 = 4
CURVE25519 = 5
UNKNOWN_FORMAT = 0
UNCOMPRESSED = 1
COMPRESSED = 2
DO_NOT_USE_CRUNCHY_UNCOMPRESSED = 3
UNKNOWN_HASH = 0
SHA1 = 1
SHA384 = 2
SHA256 = 3
SHA512 = 4
SHA224 = 5


DESCRIPTOR.enum_types_by_name['EllipticCurveType'] = _ELLIPTICCURVETYPE
DESCRIPTOR.enum_types_by_name['EcPointFormat'] = _ECPOINTFORMAT
DESCRIPTOR.enum_types_by_name['HashType'] = _HASHTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
