# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/config.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z,github.com/google/tink/proto/config_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17tink/proto/config.proto\x12\x12google.crypto.tink\"\x8a\x01\n\x0cKeyTypeEntry\x12\x16\n\x0eprimitive_name\x18\x01 \x01(\t\x12\x10\n\x08type_url\x18\x02 \x01(\t\x12\x1b\n\x13key_manager_version\x18\x03 \x01(\r\x12\x17\n\x0fnew_key_allowed\x18\x04 \x01(\x08\x12\x16\n\x0e\x63\x61talogue_name\x18\x05 \x01(\t:\x02\x18\x01\"Z\n\x0eRegistryConfig\x12\x13\n\x0b\x63onfig_name\x18\x01 \x01(\t\x12/\n\x05\x65ntry\x18\x02 \x03(\x0b\x32 .google.crypto.tink.KeyTypeEntry:\x02\x18\x01\x42N\n\x1c\x63om.google.crypto.tink.protoP\x01Z,github.com/google/tink/proto/config_go_protob\x06proto3'
)




_KEYTYPEENTRY = _descriptor.Descriptor(
  name='KeyTypeEntry',
  full_name='google.crypto.tink.KeyTypeEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='primitive_name', full_name='google.crypto.tink.KeyTypeEntry.primitive_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type_url', full_name='google.crypto.tink.KeyTypeEntry.type_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_manager_version', full_name='google.crypto.tink.KeyTypeEntry.key_manager_version', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_key_allowed', full_name='google.crypto.tink.KeyTypeEntry.new_key_allowed', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='catalogue_name', full_name='google.crypto.tink.KeyTypeEntry.catalogue_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\030\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=186,
)


_REGISTRYCONFIG = _descriptor.Descriptor(
  name='RegistryConfig',
  full_name='google.crypto.tink.RegistryConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_name', full_name='google.crypto.tink.RegistryConfig.config_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entry', full_name='google.crypto.tink.RegistryConfig.entry', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\030\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=278,
)

_REGISTRYCONFIG.fields_by_name['entry'].message_type = _KEYTYPEENTRY
DESCRIPTOR.message_types_by_name['KeyTypeEntry'] = _KEYTYPEENTRY
DESCRIPTOR.message_types_by_name['RegistryConfig'] = _REGISTRYCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyTypeEntry = _reflection.GeneratedProtocolMessageType('KeyTypeEntry', (_message.Message,), {
  'DESCRIPTOR' : _KEYTYPEENTRY,
  '__module__' : 'tink.proto.config_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.KeyTypeEntry)
  })
_sym_db.RegisterMessage(KeyTypeEntry)

RegistryConfig = _reflection.GeneratedProtocolMessageType('RegistryConfig', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRYCONFIG,
  '__module__' : 'tink.proto.config_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.RegistryConfig)
  })
_sym_db.RegisterMessage(RegistryConfig)


DESCRIPTOR._options = None
_KEYTYPEENTRY._options = None
_REGISTRYCONFIG._options = None
# @@protoc_insertion_point(module_scope)
