# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/ecdsa.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import common_pb2 as tink_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/ecdsa.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z+github.com/google/tink/proto/ecdsa_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16tink/proto/ecdsa.proto\x12\x12google.crypto.tink\x1a\x17tink/proto/common.proto\"\xb2\x01\n\x0b\x45\x63\x64saParams\x12/\n\thash_type\x18\x01 \x01(\x0e\x32\x1c.google.crypto.tink.HashType\x12\x34\n\x05\x63urve\x18\x02 \x01(\x0e\x32%.google.crypto.tink.EllipticCurveType\x12<\n\x08\x65ncoding\x18\x03 \x01(\x0e\x32*.google.crypto.tink.EcdsaSignatureEncoding\"h\n\x0e\x45\x63\x64saPublicKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12/\n\x06params\x18\x02 \x01(\x0b\x32\x1f.google.crypto.tink.EcdsaParams\x12\t\n\x01x\x18\x03 \x01(\x0c\x12\t\n\x01y\x18\x04 \x01(\x0c\"m\n\x0f\x45\x63\x64saPrivateKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x36\n\npublic_key\x18\x02 \x01(\x0b\x32\".google.crypto.tink.EcdsaPublicKey\x12\x11\n\tkey_value\x18\x03 \x01(\x0c\"A\n\x0e\x45\x63\x64saKeyFormat\x12/\n\x06params\x18\x02 \x01(\x0b\x32\x1f.google.crypto.tink.EcdsaParams*G\n\x16\x45\x63\x64saSignatureEncoding\x12\x14\n\x10UNKNOWN_ENCODING\x10\x00\x12\x0e\n\nIEEE_P1363\x10\x01\x12\x07\n\x03\x44\x45R\x10\x02\x42M\n\x1c\x63om.google.crypto.tink.protoP\x01Z+github.com/google/tink/proto/ecdsa_go_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_common__pb2.DESCRIPTOR,])

_ECDSASIGNATUREENCODING = _descriptor.EnumDescriptor(
  name='EcdsaSignatureEncoding',
  full_name='google.crypto.tink.EcdsaSignatureEncoding',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ENCODING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IEEE_P1363', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=536,
  serialized_end=607,
)
_sym_db.RegisterEnumDescriptor(_ECDSASIGNATUREENCODING)

EcdsaSignatureEncoding = enum_type_wrapper.EnumTypeWrapper(_ECDSASIGNATUREENCODING)
UNKNOWN_ENCODING = 0
IEEE_P1363 = 1
DER = 2



_ECDSAPARAMS = _descriptor.Descriptor(
  name='EcdsaParams',
  full_name='google.crypto.tink.EcdsaParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash_type', full_name='google.crypto.tink.EcdsaParams.hash_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='curve', full_name='google.crypto.tink.EcdsaParams.curve', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='google.crypto.tink.EcdsaParams.encoding', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=250,
)


_ECDSAPUBLICKEY = _descriptor.Descriptor(
  name='EcdsaPublicKey',
  full_name='google.crypto.tink.EcdsaPublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.EcdsaPublicKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.EcdsaPublicKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='google.crypto.tink.EcdsaPublicKey.x', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='google.crypto.tink.EcdsaPublicKey.y', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=356,
)


_ECDSAPRIVATEKEY = _descriptor.Descriptor(
  name='EcdsaPrivateKey',
  full_name='google.crypto.tink.EcdsaPrivateKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.EcdsaPrivateKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='google.crypto.tink.EcdsaPrivateKey.public_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.EcdsaPrivateKey.key_value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=467,
)


_ECDSAKEYFORMAT = _descriptor.Descriptor(
  name='EcdsaKeyFormat',
  full_name='google.crypto.tink.EcdsaKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.EcdsaKeyFormat.params', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=534,
)

_ECDSAPARAMS.fields_by_name['hash_type'].enum_type = tink_dot_proto_dot_common__pb2._HASHTYPE
_ECDSAPARAMS.fields_by_name['curve'].enum_type = tink_dot_proto_dot_common__pb2._ELLIPTICCURVETYPE
_ECDSAPARAMS.fields_by_name['encoding'].enum_type = _ECDSASIGNATUREENCODING
_ECDSAPUBLICKEY.fields_by_name['params'].message_type = _ECDSAPARAMS
_ECDSAPRIVATEKEY.fields_by_name['public_key'].message_type = _ECDSAPUBLICKEY
_ECDSAKEYFORMAT.fields_by_name['params'].message_type = _ECDSAPARAMS
DESCRIPTOR.message_types_by_name['EcdsaParams'] = _ECDSAPARAMS
DESCRIPTOR.message_types_by_name['EcdsaPublicKey'] = _ECDSAPUBLICKEY
DESCRIPTOR.message_types_by_name['EcdsaPrivateKey'] = _ECDSAPRIVATEKEY
DESCRIPTOR.message_types_by_name['EcdsaKeyFormat'] = _ECDSAKEYFORMAT
DESCRIPTOR.enum_types_by_name['EcdsaSignatureEncoding'] = _ECDSASIGNATUREENCODING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EcdsaParams = _reflection.GeneratedProtocolMessageType('EcdsaParams', (_message.Message,), {
  'DESCRIPTOR' : _ECDSAPARAMS,
  '__module__' : 'tink.proto.ecdsa_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.EcdsaParams)
  })
_sym_db.RegisterMessage(EcdsaParams)

EcdsaPublicKey = _reflection.GeneratedProtocolMessageType('EcdsaPublicKey', (_message.Message,), {
  'DESCRIPTOR' : _ECDSAPUBLICKEY,
  '__module__' : 'tink.proto.ecdsa_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.EcdsaPublicKey)
  })
_sym_db.RegisterMessage(EcdsaPublicKey)

EcdsaPrivateKey = _reflection.GeneratedProtocolMessageType('EcdsaPrivateKey', (_message.Message,), {
  'DESCRIPTOR' : _ECDSAPRIVATEKEY,
  '__module__' : 'tink.proto.ecdsa_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.EcdsaPrivateKey)
  })
_sym_db.RegisterMessage(EcdsaPrivateKey)

EcdsaKeyFormat = _reflection.GeneratedProtocolMessageType('EcdsaKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _ECDSAKEYFORMAT,
  '__module__' : 'tink.proto.ecdsa_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.EcdsaKeyFormat)
  })
_sym_db.RegisterMessage(EcdsaKeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
