# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/ecies_aead_hkdf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import common_pb2 as tink_dot_proto_dot_common__pb2
from tink.proto import tink_pb2 as tink_dot_proto_dot_tink__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/ecies_aead_hkdf.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z5github.com/google/tink/proto/ecies_aead_hkdf_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n tink/proto/ecies_aead_hkdf.proto\x12\x12google.crypto.tink\x1a\x17tink/proto/common.proto\x1a\x15tink/proto/tink.proto\"\x98\x01\n\x12\x45\x63iesHkdfKemParams\x12\x39\n\ncurve_type\x18\x01 \x01(\x0e\x32%.google.crypto.tink.EllipticCurveType\x12\x34\n\x0ehkdf_hash_type\x18\x02 \x01(\x0e\x32\x1c.google.crypto.tink.HashType\x12\x11\n\thkdf_salt\x18\x0b \x01(\x0c\"G\n\x12\x45\x63iesAeadDemParams\x12\x31\n\x08\x61\x65\x61\x64_dem\x18\x02 \x01(\x0b\x32\x1f.google.crypto.tink.KeyTemplate\"\xc9\x01\n\x13\x45\x63iesAeadHkdfParams\x12:\n\nkem_params\x18\x01 \x01(\x0b\x32&.google.crypto.tink.EciesHkdfKemParams\x12:\n\ndem_params\x18\x02 \x01(\x0b\x32&.google.crypto.tink.EciesAeadDemParams\x12:\n\x0f\x65\x63_point_format\x18\x03 \x01(\x0e\x32!.google.crypto.tink.EcPointFormat\"x\n\x16\x45\x63iesAeadHkdfPublicKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x37\n\x06params\x18\x02 \x01(\x0b\x32\'.google.crypto.tink.EciesAeadHkdfParams\x12\t\n\x01x\x18\x03 \x01(\x0c\x12\t\n\x01y\x18\x04 \x01(\x0c\"}\n\x17\x45\x63iesAeadHkdfPrivateKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12>\n\npublic_key\x18\x02 \x01(\x0b\x32*.google.crypto.tink.EciesAeadHkdfPublicKey\x12\x11\n\tkey_value\x18\x03 \x01(\x0c\"Q\n\x16\x45\x63iesAeadHkdfKeyFormat\x12\x37\n\x06params\x18\x01 \x01(\x0b\x32\'.google.crypto.tink.EciesAeadHkdfParamsBW\n\x1c\x63om.google.crypto.tink.protoP\x01Z5github.com/google/tink/proto/ecies_aead_hkdf_go_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_common__pb2.DESCRIPTOR,tink_dot_proto_dot_tink__pb2.DESCRIPTOR,])




_ECIESHKDFKEMPARAMS = _descriptor.Descriptor(
  name='EciesHkdfKemParams',
  full_name='google.crypto.tink.EciesHkdfKemParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='curve_type', full_name='google.crypto.tink.EciesHkdfKemParams.curve_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hkdf_hash_type', full_name='google.crypto.tink.EciesHkdfKemParams.hkdf_hash_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hkdf_salt', full_name='google.crypto.tink.EciesHkdfKemParams.hkdf_salt', index=2,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=257,
)


_ECIESAEADDEMPARAMS = _descriptor.Descriptor(
  name='EciesAeadDemParams',
  full_name='google.crypto.tink.EciesAeadDemParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='aead_dem', full_name='google.crypto.tink.EciesAeadDemParams.aead_dem', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=330,
)


_ECIESAEADHKDFPARAMS = _descriptor.Descriptor(
  name='EciesAeadHkdfParams',
  full_name='google.crypto.tink.EciesAeadHkdfParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kem_params', full_name='google.crypto.tink.EciesAeadHkdfParams.kem_params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dem_params', full_name='google.crypto.tink.EciesAeadHkdfParams.dem_params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ec_point_format', full_name='google.crypto.tink.EciesAeadHkdfParams.ec_point_format', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=534,
)


_ECIESAEADHKDFPUBLICKEY = _descriptor.Descriptor(
  name='EciesAeadHkdfPublicKey',
  full_name='google.crypto.tink.EciesAeadHkdfPublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.EciesAeadHkdfPublicKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.EciesAeadHkdfPublicKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='google.crypto.tink.EciesAeadHkdfPublicKey.x', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='google.crypto.tink.EciesAeadHkdfPublicKey.y', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=536,
  serialized_end=656,
)


_ECIESAEADHKDFPRIVATEKEY = _descriptor.Descriptor(
  name='EciesAeadHkdfPrivateKey',
  full_name='google.crypto.tink.EciesAeadHkdfPrivateKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.EciesAeadHkdfPrivateKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='google.crypto.tink.EciesAeadHkdfPrivateKey.public_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.EciesAeadHkdfPrivateKey.key_value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=658,
  serialized_end=783,
)


_ECIESAEADHKDFKEYFORMAT = _descriptor.Descriptor(
  name='EciesAeadHkdfKeyFormat',
  full_name='google.crypto.tink.EciesAeadHkdfKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.EciesAeadHkdfKeyFormat.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=785,
  serialized_end=866,
)

_ECIESHKDFKEMPARAMS.fields_by_name['curve_type'].enum_type = tink_dot_proto_dot_common__pb2._ELLIPTICCURVETYPE
_ECIESHKDFKEMPARAMS.fields_by_name['hkdf_hash_type'].enum_type = tink_dot_proto_dot_common__pb2._HASHTYPE
_ECIESAEADDEMPARAMS.fields_by_name['aead_dem'].message_type = tink_dot_proto_dot_tink__pb2._KEYTEMPLATE
_ECIESAEADHKDFPARAMS.fields_by_name['kem_params'].message_type = _ECIESHKDFKEMPARAMS
_ECIESAEADHKDFPARAMS.fields_by_name['dem_params'].message_type = _ECIESAEADDEMPARAMS
_ECIESAEADHKDFPARAMS.fields_by_name['ec_point_format'].enum_type = tink_dot_proto_dot_common__pb2._ECPOINTFORMAT
_ECIESAEADHKDFPUBLICKEY.fields_by_name['params'].message_type = _ECIESAEADHKDFPARAMS
_ECIESAEADHKDFPRIVATEKEY.fields_by_name['public_key'].message_type = _ECIESAEADHKDFPUBLICKEY
_ECIESAEADHKDFKEYFORMAT.fields_by_name['params'].message_type = _ECIESAEADHKDFPARAMS
DESCRIPTOR.message_types_by_name['EciesHkdfKemParams'] = _ECIESHKDFKEMPARAMS
DESCRIPTOR.message_types_by_name['EciesAeadDemParams'] = _ECIESAEADDEMPARAMS
DESCRIPTOR.message_types_by_name['EciesAeadHkdfParams'] = _ECIESAEADHKDFPARAMS
DESCRIPTOR.message_types_by_name['EciesAeadHkdfPublicKey'] = _ECIESAEADHKDFPUBLICKEY
DESCRIPTOR.message_types_by_name['EciesAeadHkdfPrivateKey'] = _ECIESAEADHKDFPRIVATEKEY
DESCRIPTOR.message_types_by_name['EciesAeadHkdfKeyFormat'] = _ECIESAEADHKDFKEYFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EciesHkdfKemParams = _reflection.GeneratedProtocolMessageType('EciesHkdfKemParams', (_message.Message,), {
  'DESCRIPTOR' : _ECIESHKDFKEMPARAMS,
  '__module__' : 'tink.proto.ecies_aead_hkdf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.EciesHkdfKemParams)
  })
_sym_db.RegisterMessage(EciesHkdfKemParams)

EciesAeadDemParams = _reflection.GeneratedProtocolMessageType('EciesAeadDemParams', (_message.Message,), {
  'DESCRIPTOR' : _ECIESAEADDEMPARAMS,
  '__module__' : 'tink.proto.ecies_aead_hkdf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.EciesAeadDemParams)
  })
_sym_db.RegisterMessage(EciesAeadDemParams)

EciesAeadHkdfParams = _reflection.GeneratedProtocolMessageType('EciesAeadHkdfParams', (_message.Message,), {
  'DESCRIPTOR' : _ECIESAEADHKDFPARAMS,
  '__module__' : 'tink.proto.ecies_aead_hkdf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.EciesAeadHkdfParams)
  })
_sym_db.RegisterMessage(EciesAeadHkdfParams)

EciesAeadHkdfPublicKey = _reflection.GeneratedProtocolMessageType('EciesAeadHkdfPublicKey', (_message.Message,), {
  'DESCRIPTOR' : _ECIESAEADHKDFPUBLICKEY,
  '__module__' : 'tink.proto.ecies_aead_hkdf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.EciesAeadHkdfPublicKey)
  })
_sym_db.RegisterMessage(EciesAeadHkdfPublicKey)

EciesAeadHkdfPrivateKey = _reflection.GeneratedProtocolMessageType('EciesAeadHkdfPrivateKey', (_message.Message,), {
  'DESCRIPTOR' : _ECIESAEADHKDFPRIVATEKEY,
  '__module__' : 'tink.proto.ecies_aead_hkdf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.EciesAeadHkdfPrivateKey)
  })
_sym_db.RegisterMessage(EciesAeadHkdfPrivateKey)

EciesAeadHkdfKeyFormat = _reflection.GeneratedProtocolMessageType('EciesAeadHkdfKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _ECIESAEADHKDFKEYFORMAT,
  '__module__' : 'tink.proto.ecies_aead_hkdf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.EciesAeadHkdfKeyFormat)
  })
_sym_db.RegisterMessage(EciesAeadHkdfKeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
