# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/ed25519.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/ed25519.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z-github.com/google/tink/proto/ed25519_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18tink/proto/ed25519.proto\x12\x12google.crypto.tink\"#\n\x10\x45\x64\x32\x35\x35\x31\x39KeyFormat\x12\x0f\n\x07version\x18\x01 \x01(\r\"6\n\x10\x45\x64\x32\x35\x35\x31\x39PublicKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tkey_value\x18\x02 \x01(\x0c\"q\n\x11\x45\x64\x32\x35\x35\x31\x39PrivateKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tkey_value\x18\x02 \x01(\x0c\x12\x38\n\npublic_key\x18\x03 \x01(\x0b\x32$.google.crypto.tink.Ed25519PublicKeyBO\n\x1c\x63om.google.crypto.tink.protoP\x01Z-github.com/google/tink/proto/ed25519_go_protob\x06proto3'
)




_ED25519KEYFORMAT = _descriptor.Descriptor(
  name='Ed25519KeyFormat',
  full_name='google.crypto.tink.Ed25519KeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.Ed25519KeyFormat.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=83,
)


_ED25519PUBLICKEY = _descriptor.Descriptor(
  name='Ed25519PublicKey',
  full_name='google.crypto.tink.Ed25519PublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.Ed25519PublicKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.Ed25519PublicKey.key_value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=139,
)


_ED25519PRIVATEKEY = _descriptor.Descriptor(
  name='Ed25519PrivateKey',
  full_name='google.crypto.tink.Ed25519PrivateKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.Ed25519PrivateKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.Ed25519PrivateKey.key_value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='google.crypto.tink.Ed25519PrivateKey.public_key', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=254,
)

_ED25519PRIVATEKEY.fields_by_name['public_key'].message_type = _ED25519PUBLICKEY
DESCRIPTOR.message_types_by_name['Ed25519KeyFormat'] = _ED25519KEYFORMAT
DESCRIPTOR.message_types_by_name['Ed25519PublicKey'] = _ED25519PUBLICKEY
DESCRIPTOR.message_types_by_name['Ed25519PrivateKey'] = _ED25519PRIVATEKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ed25519KeyFormat = _reflection.GeneratedProtocolMessageType('Ed25519KeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _ED25519KEYFORMAT,
  '__module__' : 'tink.proto.ed25519_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.Ed25519KeyFormat)
  })
_sym_db.RegisterMessage(Ed25519KeyFormat)

Ed25519PublicKey = _reflection.GeneratedProtocolMessageType('Ed25519PublicKey', (_message.Message,), {
  'DESCRIPTOR' : _ED25519PUBLICKEY,
  '__module__' : 'tink.proto.ed25519_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.Ed25519PublicKey)
  })
_sym_db.RegisterMessage(Ed25519PublicKey)

Ed25519PrivateKey = _reflection.GeneratedProtocolMessageType('Ed25519PrivateKey', (_message.Message,), {
  'DESCRIPTOR' : _ED25519PRIVATEKEY,
  '__module__' : 'tink.proto.ed25519_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.Ed25519PrivateKey)
  })
_sym_db.RegisterMessage(Ed25519PrivateKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
