# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/empty.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/empty.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z+github.com/google/tink/proto/empty_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16tink/proto/empty.proto\x12\x12google.crypto.tink\"\x07\n\x05\x45mptyBM\n\x1c\x63om.google.crypto.tink.protoP\x01Z+github.com/google/tink/proto/empty_go_protob\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='google.crypto.tink.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'tink.proto.empty_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
