# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/hkdf_prf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import common_pb2 as tink_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/hkdf_prf.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z+github.com/google/tink/proto/hkdf_prf_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19tink/proto/hkdf_prf.proto\x12\x12google.crypto.tink\x1a\x17tink/proto/common.proto\"I\n\rHkdfPrfParams\x12*\n\x04hash\x18\x01 \x01(\x0e\x32\x1c.google.crypto.tink.HashType\x12\x0c\n\x04salt\x18\x02 \x01(\x0c\"c\n\nHkdfPrfKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x31\n\x06params\x18\x02 \x01(\x0b\x32!.google.crypto.tink.HkdfPrfParams\x12\x11\n\tkey_value\x18\x03 \x01(\x0c\"h\n\x10HkdfPrfKeyFormat\x12\x31\n\x06params\x18\x01 \x01(\x0b\x32!.google.crypto.tink.HkdfPrfParams\x12\x10\n\x08key_size\x18\x02 \x01(\r\x12\x0f\n\x07version\x18\x03 \x01(\rBM\n\x1c\x63om.google.crypto.tink.protoP\x01Z+github.com/google/tink/proto/hkdf_prf_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_common__pb2.DESCRIPTOR,])




_HKDFPRFPARAMS = _descriptor.Descriptor(
  name='HkdfPrfParams',
  full_name='google.crypto.tink.HkdfPrfParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='google.crypto.tink.HkdfPrfParams.hash', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='salt', full_name='google.crypto.tink.HkdfPrfParams.salt', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=147,
)


_HKDFPRFKEY = _descriptor.Descriptor(
  name='HkdfPrfKey',
  full_name='google.crypto.tink.HkdfPrfKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.HkdfPrfKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.HkdfPrfKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.HkdfPrfKey.key_value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=248,
)


_HKDFPRFKEYFORMAT = _descriptor.Descriptor(
  name='HkdfPrfKeyFormat',
  full_name='google.crypto.tink.HkdfPrfKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.HkdfPrfKeyFormat.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_size', full_name='google.crypto.tink.HkdfPrfKeyFormat.key_size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.HkdfPrfKeyFormat.version', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=354,
)

_HKDFPRFPARAMS.fields_by_name['hash'].enum_type = tink_dot_proto_dot_common__pb2._HASHTYPE
_HKDFPRFKEY.fields_by_name['params'].message_type = _HKDFPRFPARAMS
_HKDFPRFKEYFORMAT.fields_by_name['params'].message_type = _HKDFPRFPARAMS
DESCRIPTOR.message_types_by_name['HkdfPrfParams'] = _HKDFPRFPARAMS
DESCRIPTOR.message_types_by_name['HkdfPrfKey'] = _HKDFPRFKEY
DESCRIPTOR.message_types_by_name['HkdfPrfKeyFormat'] = _HKDFPRFKEYFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HkdfPrfParams = _reflection.GeneratedProtocolMessageType('HkdfPrfParams', (_message.Message,), {
  'DESCRIPTOR' : _HKDFPRFPARAMS,
  '__module__' : 'tink.proto.hkdf_prf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HkdfPrfParams)
  })
_sym_db.RegisterMessage(HkdfPrfParams)

HkdfPrfKey = _reflection.GeneratedProtocolMessageType('HkdfPrfKey', (_message.Message,), {
  'DESCRIPTOR' : _HKDFPRFKEY,
  '__module__' : 'tink.proto.hkdf_prf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HkdfPrfKey)
  })
_sym_db.RegisterMessage(HkdfPrfKey)

HkdfPrfKeyFormat = _reflection.GeneratedProtocolMessageType('HkdfPrfKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _HKDFPRFKEYFORMAT,
  '__module__' : 'tink.proto.hkdf_prf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HkdfPrfKeyFormat)
  })
_sym_db.RegisterMessage(HkdfPrfKeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
