# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/hmac_prf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import common_pb2 as tink_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/hmac_prf.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z.github.com/google/tink/proto/hmac_prf_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19tink/proto/hmac_prf.proto\x12\x12google.crypto.tink\x1a\x17tink/proto/common.proto\";\n\rHmacPrfParams\x12*\n\x04hash\x18\x01 \x01(\x0e\x32\x1c.google.crypto.tink.HashType\"c\n\nHmacPrfKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x31\n\x06params\x18\x02 \x01(\x0b\x32!.google.crypto.tink.HmacPrfParams\x12\x11\n\tkey_value\x18\x03 \x01(\x0c\"h\n\x10HmacPrfKeyFormat\x12\x31\n\x06params\x18\x01 \x01(\x0b\x32!.google.crypto.tink.HmacPrfParams\x12\x10\n\x08key_size\x18\x02 \x01(\r\x12\x0f\n\x07version\x18\x03 \x01(\rBP\n\x1c\x63om.google.crypto.tink.protoP\x01Z.github.com/google/tink/proto/hmac_prf_go_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_common__pb2.DESCRIPTOR,])




_HMACPRFPARAMS = _descriptor.Descriptor(
  name='HmacPrfParams',
  full_name='google.crypto.tink.HmacPrfParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='google.crypto.tink.HmacPrfParams.hash', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=133,
)


_HMACPRFKEY = _descriptor.Descriptor(
  name='HmacPrfKey',
  full_name='google.crypto.tink.HmacPrfKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.HmacPrfKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.HmacPrfKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.HmacPrfKey.key_value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=234,
)


_HMACPRFKEYFORMAT = _descriptor.Descriptor(
  name='HmacPrfKeyFormat',
  full_name='google.crypto.tink.HmacPrfKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.HmacPrfKeyFormat.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_size', full_name='google.crypto.tink.HmacPrfKeyFormat.key_size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.HmacPrfKeyFormat.version', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=340,
)

_HMACPRFPARAMS.fields_by_name['hash'].enum_type = tink_dot_proto_dot_common__pb2._HASHTYPE
_HMACPRFKEY.fields_by_name['params'].message_type = _HMACPRFPARAMS
_HMACPRFKEYFORMAT.fields_by_name['params'].message_type = _HMACPRFPARAMS
DESCRIPTOR.message_types_by_name['HmacPrfParams'] = _HMACPRFPARAMS
DESCRIPTOR.message_types_by_name['HmacPrfKey'] = _HMACPRFKEY
DESCRIPTOR.message_types_by_name['HmacPrfKeyFormat'] = _HMACPRFKEYFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HmacPrfParams = _reflection.GeneratedProtocolMessageType('HmacPrfParams', (_message.Message,), {
  'DESCRIPTOR' : _HMACPRFPARAMS,
  '__module__' : 'tink.proto.hmac_prf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HmacPrfParams)
  })
_sym_db.RegisterMessage(HmacPrfParams)

HmacPrfKey = _reflection.GeneratedProtocolMessageType('HmacPrfKey', (_message.Message,), {
  'DESCRIPTOR' : _HMACPRFKEY,
  '__module__' : 'tink.proto.hmac_prf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HmacPrfKey)
  })
_sym_db.RegisterMessage(HmacPrfKey)

HmacPrfKeyFormat = _reflection.GeneratedProtocolMessageType('HmacPrfKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _HMACPRFKEYFORMAT,
  '__module__' : 'tink.proto.hmac_prf_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HmacPrfKeyFormat)
  })
_sym_db.RegisterMessage(HmacPrfKeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
