# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/hmac.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import common_pb2 as tink_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/hmac.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z*github.com/google/tink/proto/hmac_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15tink/proto/hmac.proto\x12\x12google.crypto.tink\x1a\x17tink/proto/common.proto\"J\n\nHmacParams\x12*\n\x04hash\x18\x01 \x01(\x0e\x32\x1c.google.crypto.tink.HashType\x12\x10\n\x08tag_size\x18\x02 \x01(\r\"]\n\x07HmacKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12.\n\x06params\x18\x02 \x01(\x0b\x32\x1e.google.crypto.tink.HmacParams\x12\x11\n\tkey_value\x18\x03 \x01(\x0c\"b\n\rHmacKeyFormat\x12.\n\x06params\x18\x01 \x01(\x0b\x32\x1e.google.crypto.tink.HmacParams\x12\x10\n\x08key_size\x18\x02 \x01(\r\x12\x0f\n\x07version\x18\x03 \x01(\rBL\n\x1c\x63om.google.crypto.tink.protoP\x01Z*github.com/google/tink/proto/hmac_go_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_common__pb2.DESCRIPTOR,])




_HMACPARAMS = _descriptor.Descriptor(
  name='HmacParams',
  full_name='google.crypto.tink.HmacParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='google.crypto.tink.HmacParams.hash', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag_size', full_name='google.crypto.tink.HmacParams.tag_size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=144,
)


_HMACKEY = _descriptor.Descriptor(
  name='HmacKey',
  full_name='google.crypto.tink.HmacKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.HmacKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.HmacKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.HmacKey.key_value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=239,
)


_HMACKEYFORMAT = _descriptor.Descriptor(
  name='HmacKeyFormat',
  full_name='google.crypto.tink.HmacKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.HmacKeyFormat.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_size', full_name='google.crypto.tink.HmacKeyFormat.key_size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.HmacKeyFormat.version', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=339,
)

_HMACPARAMS.fields_by_name['hash'].enum_type = tink_dot_proto_dot_common__pb2._HASHTYPE
_HMACKEY.fields_by_name['params'].message_type = _HMACPARAMS
_HMACKEYFORMAT.fields_by_name['params'].message_type = _HMACPARAMS
DESCRIPTOR.message_types_by_name['HmacParams'] = _HMACPARAMS
DESCRIPTOR.message_types_by_name['HmacKey'] = _HMACKEY
DESCRIPTOR.message_types_by_name['HmacKeyFormat'] = _HMACKEYFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HmacParams = _reflection.GeneratedProtocolMessageType('HmacParams', (_message.Message,), {
  'DESCRIPTOR' : _HMACPARAMS,
  '__module__' : 'tink.proto.hmac_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HmacParams)
  })
_sym_db.RegisterMessage(HmacParams)

HmacKey = _reflection.GeneratedProtocolMessageType('HmacKey', (_message.Message,), {
  'DESCRIPTOR' : _HMACKEY,
  '__module__' : 'tink.proto.hmac_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HmacKey)
  })
_sym_db.RegisterMessage(HmacKey)

HmacKeyFormat = _reflection.GeneratedProtocolMessageType('HmacKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _HMACKEYFORMAT,
  '__module__' : 'tink.proto.hmac_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HmacKeyFormat)
  })
_sym_db.RegisterMessage(HmacKeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
