# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/hpke.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/hpke.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z\'github.com/google/tink/proto/hpke_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15tink/proto/hpke.proto\x12\x12google.crypto.tink\"\x8c\x01\n\nHpkeParams\x12(\n\x03kem\x18\x01 \x01(\x0e\x32\x1b.google.crypto.tink.HpkeKem\x12(\n\x03kdf\x18\x02 \x01(\x0e\x32\x1b.google.crypto.tink.HpkeKdf\x12*\n\x04\x61\x65\x61\x64\x18\x03 \x01(\x0e\x32\x1c.google.crypto.tink.HpkeAead\"d\n\rHpkePublicKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12.\n\x06params\x18\x02 \x01(\x0b\x32\x1e.google.crypto.tink.HpkeParams\x12\x12\n\npublic_key\x18\x03 \x01(\x0c\"m\n\x0eHpkePrivateKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x35\n\npublic_key\x18\x02 \x01(\x0b\x32!.google.crypto.tink.HpkePublicKey\x12\x13\n\x0bprivate_key\x18\x03 \x01(\x0c\"?\n\rHpkeKeyFormat\x12.\n\x06params\x18\x01 \x01(\x0b\x32\x1e.google.crypto.tink.HpkeParams*8\n\x07HpkeKem\x12\x0f\n\x0bKEM_UNKNOWN\x10\x00\x12\x1c\n\x18\x44HKEM_X25519_HKDF_SHA256\x10\x01*+\n\x07HpkeKdf\x12\x0f\n\x0bKDF_UNKNOWN\x10\x00\x12\x0f\n\x0bHKDF_SHA256\x10\x01*U\n\x08HpkeAead\x12\x10\n\x0c\x41\x45\x41\x44_UNKNOWN\x10\x00\x12\x0f\n\x0b\x41\x45S_128_GCM\x10\x01\x12\x0f\n\x0b\x41\x45S_256_GCM\x10\x02\x12\x15\n\x11\x43HACHA20_POLY1305\x10\x03\x42I\n\x1c\x63om.google.crypto.tink.protoP\x01Z\'github.com/google/tink/proto/hpke_protob\x06proto3'
)

_HPKEKEM = _descriptor.EnumDescriptor(
  name='HpkeKem',
  full_name='google.crypto.tink.HpkeKem',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KEM_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DHKEM_X25519_HKDF_SHA256', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=466,
  serialized_end=522,
)
_sym_db.RegisterEnumDescriptor(_HPKEKEM)

HpkeKem = enum_type_wrapper.EnumTypeWrapper(_HPKEKEM)
_HPKEKDF = _descriptor.EnumDescriptor(
  name='HpkeKdf',
  full_name='google.crypto.tink.HpkeKdf',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KDF_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HKDF_SHA256', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=524,
  serialized_end=567,
)
_sym_db.RegisterEnumDescriptor(_HPKEKDF)

HpkeKdf = enum_type_wrapper.EnumTypeWrapper(_HPKEKDF)
_HPKEAEAD = _descriptor.EnumDescriptor(
  name='HpkeAead',
  full_name='google.crypto.tink.HpkeAead',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AEAD_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AES_128_GCM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AES_256_GCM', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHACHA20_POLY1305', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=569,
  serialized_end=654,
)
_sym_db.RegisterEnumDescriptor(_HPKEAEAD)

HpkeAead = enum_type_wrapper.EnumTypeWrapper(_HPKEAEAD)
KEM_UNKNOWN = 0
DHKEM_X25519_HKDF_SHA256 = 1
KDF_UNKNOWN = 0
HKDF_SHA256 = 1
AEAD_UNKNOWN = 0
AES_128_GCM = 1
AES_256_GCM = 2
CHACHA20_POLY1305 = 3



_HPKEPARAMS = _descriptor.Descriptor(
  name='HpkeParams',
  full_name='google.crypto.tink.HpkeParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kem', full_name='google.crypto.tink.HpkeParams.kem', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kdf', full_name='google.crypto.tink.HpkeParams.kdf', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aead', full_name='google.crypto.tink.HpkeParams.aead', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=186,
)


_HPKEPUBLICKEY = _descriptor.Descriptor(
  name='HpkePublicKey',
  full_name='google.crypto.tink.HpkePublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.HpkePublicKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.HpkePublicKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='google.crypto.tink.HpkePublicKey.public_key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=288,
)


_HPKEPRIVATEKEY = _descriptor.Descriptor(
  name='HpkePrivateKey',
  full_name='google.crypto.tink.HpkePrivateKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.HpkePrivateKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='google.crypto.tink.HpkePrivateKey.public_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='private_key', full_name='google.crypto.tink.HpkePrivateKey.private_key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=399,
)


_HPKEKEYFORMAT = _descriptor.Descriptor(
  name='HpkeKeyFormat',
  full_name='google.crypto.tink.HpkeKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.HpkeKeyFormat.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=464,
)

_HPKEPARAMS.fields_by_name['kem'].enum_type = _HPKEKEM
_HPKEPARAMS.fields_by_name['kdf'].enum_type = _HPKEKDF
_HPKEPARAMS.fields_by_name['aead'].enum_type = _HPKEAEAD
_HPKEPUBLICKEY.fields_by_name['params'].message_type = _HPKEPARAMS
_HPKEPRIVATEKEY.fields_by_name['public_key'].message_type = _HPKEPUBLICKEY
_HPKEKEYFORMAT.fields_by_name['params'].message_type = _HPKEPARAMS
DESCRIPTOR.message_types_by_name['HpkeParams'] = _HPKEPARAMS
DESCRIPTOR.message_types_by_name['HpkePublicKey'] = _HPKEPUBLICKEY
DESCRIPTOR.message_types_by_name['HpkePrivateKey'] = _HPKEPRIVATEKEY
DESCRIPTOR.message_types_by_name['HpkeKeyFormat'] = _HPKEKEYFORMAT
DESCRIPTOR.enum_types_by_name['HpkeKem'] = _HPKEKEM
DESCRIPTOR.enum_types_by_name['HpkeKdf'] = _HPKEKDF
DESCRIPTOR.enum_types_by_name['HpkeAead'] = _HPKEAEAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HpkeParams = _reflection.GeneratedProtocolMessageType('HpkeParams', (_message.Message,), {
  'DESCRIPTOR' : _HPKEPARAMS,
  '__module__' : 'tink.proto.hpke_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HpkeParams)
  })
_sym_db.RegisterMessage(HpkeParams)

HpkePublicKey = _reflection.GeneratedProtocolMessageType('HpkePublicKey', (_message.Message,), {
  'DESCRIPTOR' : _HPKEPUBLICKEY,
  '__module__' : 'tink.proto.hpke_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HpkePublicKey)
  })
_sym_db.RegisterMessage(HpkePublicKey)

HpkePrivateKey = _reflection.GeneratedProtocolMessageType('HpkePrivateKey', (_message.Message,), {
  'DESCRIPTOR' : _HPKEPRIVATEKEY,
  '__module__' : 'tink.proto.hpke_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HpkePrivateKey)
  })
_sym_db.RegisterMessage(HpkePrivateKey)

HpkeKeyFormat = _reflection.GeneratedProtocolMessageType('HpkeKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _HPKEKEYFORMAT,
  '__module__' : 'tink.proto.hpke_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.HpkeKeyFormat)
  })
_sym_db.RegisterMessage(HpkeKeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
