# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/jwt_rsa_ssa_pkcs1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/jwt_rsa_ssa_pkcs1.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z3github.com/google/tink/proto/rsa_ssa_pkcs1_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"tink/proto/jwt_rsa_ssa_pkcs1.proto\x12\x12google.crypto.tink\"\xe7\x01\n\x17JwtRsaSsaPkcs1PublicKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12>\n\talgorithm\x18\x02 \x01(\x0e\x32+.google.crypto.tink.JwtRsaSsaPkcs1Algorithm\x12\t\n\x01n\x18\x03 \x01(\x0c\x12\t\n\x01\x65\x18\x04 \x01(\x0c\x12I\n\ncustom_kid\x18\x05 \x01(\x0b\x32\x35.google.crypto.tink.JwtRsaSsaPkcs1PublicKey.CustomKid\x1a\x1a\n\tCustomKid\x12\r\n\x05value\x18\x01 \x01(\t\"\xb2\x01\n\x18JwtRsaSsaPkcs1PrivateKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12?\n\npublic_key\x18\x02 \x01(\x0b\x32+.google.crypto.tink.JwtRsaSsaPkcs1PublicKey\x12\t\n\x01\x64\x18\x03 \x01(\x0c\x12\t\n\x01p\x18\x04 \x01(\x0c\x12\t\n\x01q\x18\x05 \x01(\x0c\x12\n\n\x02\x64p\x18\x06 \x01(\x0c\x12\n\n\x02\x64q\x18\x07 \x01(\x0c\x12\x0b\n\x03\x63rt\x18\x08 \x01(\x0c\"\xa1\x01\n\x17JwtRsaSsaPkcs1KeyFormat\x12\x0f\n\x07version\x18\x01 \x01(\r\x12>\n\talgorithm\x18\x02 \x01(\x0e\x32+.google.crypto.tink.JwtRsaSsaPkcs1Algorithm\x12\x1c\n\x14modulus_size_in_bits\x18\x03 \x01(\r\x12\x17\n\x0fpublic_exponent\x18\x04 \x01(\x0c*J\n\x17JwtRsaSsaPkcs1Algorithm\x12\x0e\n\nRS_UNKNOWN\x10\x00\x12\t\n\x05RS256\x10\x01\x12\t\n\x05RS384\x10\x02\x12\t\n\x05RS512\x10\x03\x42U\n\x1c\x63om.google.crypto.tink.protoP\x01Z3github.com/google/tink/proto/rsa_ssa_pkcs1_go_protob\x06proto3'
)

_JWTRSASSAPKCS1ALGORITHM = _descriptor.EnumDescriptor(
  name='JwtRsaSsaPkcs1Algorithm',
  full_name='google.crypto.tink.JwtRsaSsaPkcs1Algorithm',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RS256', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RS384', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RS512', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=637,
  serialized_end=711,
)
_sym_db.RegisterEnumDescriptor(_JWTRSASSAPKCS1ALGORITHM)

JwtRsaSsaPkcs1Algorithm = enum_type_wrapper.EnumTypeWrapper(_JWTRSASSAPKCS1ALGORITHM)
RS_UNKNOWN = 0
RS256 = 1
RS384 = 2
RS512 = 3



_JWTRSASSAPKCS1PUBLICKEY_CUSTOMKID = _descriptor.Descriptor(
  name='CustomKid',
  full_name='google.crypto.tink.JwtRsaSsaPkcs1PublicKey.CustomKid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='google.crypto.tink.JwtRsaSsaPkcs1PublicKey.CustomKid.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=290,
)

_JWTRSASSAPKCS1PUBLICKEY = _descriptor.Descriptor(
  name='JwtRsaSsaPkcs1PublicKey',
  full_name='google.crypto.tink.JwtRsaSsaPkcs1PublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.JwtRsaSsaPkcs1PublicKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='google.crypto.tink.JwtRsaSsaPkcs1PublicKey.algorithm', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n', full_name='google.crypto.tink.JwtRsaSsaPkcs1PublicKey.n', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='e', full_name='google.crypto.tink.JwtRsaSsaPkcs1PublicKey.e', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='custom_kid', full_name='google.crypto.tink.JwtRsaSsaPkcs1PublicKey.custom_kid', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_JWTRSASSAPKCS1PUBLICKEY_CUSTOMKID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=290,
)


_JWTRSASSAPKCS1PRIVATEKEY = _descriptor.Descriptor(
  name='JwtRsaSsaPkcs1PrivateKey',
  full_name='google.crypto.tink.JwtRsaSsaPkcs1PrivateKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.JwtRsaSsaPkcs1PrivateKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='google.crypto.tink.JwtRsaSsaPkcs1PrivateKey.public_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d', full_name='google.crypto.tink.JwtRsaSsaPkcs1PrivateKey.d', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p', full_name='google.crypto.tink.JwtRsaSsaPkcs1PrivateKey.p', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q', full_name='google.crypto.tink.JwtRsaSsaPkcs1PrivateKey.q', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dp', full_name='google.crypto.tink.JwtRsaSsaPkcs1PrivateKey.dp', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dq', full_name='google.crypto.tink.JwtRsaSsaPkcs1PrivateKey.dq', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crt', full_name='google.crypto.tink.JwtRsaSsaPkcs1PrivateKey.crt', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=471,
)


_JWTRSASSAPKCS1KEYFORMAT = _descriptor.Descriptor(
  name='JwtRsaSsaPkcs1KeyFormat',
  full_name='google.crypto.tink.JwtRsaSsaPkcs1KeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.JwtRsaSsaPkcs1KeyFormat.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='google.crypto.tink.JwtRsaSsaPkcs1KeyFormat.algorithm', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='modulus_size_in_bits', full_name='google.crypto.tink.JwtRsaSsaPkcs1KeyFormat.modulus_size_in_bits', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_exponent', full_name='google.crypto.tink.JwtRsaSsaPkcs1KeyFormat.public_exponent', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=635,
)

_JWTRSASSAPKCS1PUBLICKEY_CUSTOMKID.containing_type = _JWTRSASSAPKCS1PUBLICKEY
_JWTRSASSAPKCS1PUBLICKEY.fields_by_name['algorithm'].enum_type = _JWTRSASSAPKCS1ALGORITHM
_JWTRSASSAPKCS1PUBLICKEY.fields_by_name['custom_kid'].message_type = _JWTRSASSAPKCS1PUBLICKEY_CUSTOMKID
_JWTRSASSAPKCS1PRIVATEKEY.fields_by_name['public_key'].message_type = _JWTRSASSAPKCS1PUBLICKEY
_JWTRSASSAPKCS1KEYFORMAT.fields_by_name['algorithm'].enum_type = _JWTRSASSAPKCS1ALGORITHM
DESCRIPTOR.message_types_by_name['JwtRsaSsaPkcs1PublicKey'] = _JWTRSASSAPKCS1PUBLICKEY
DESCRIPTOR.message_types_by_name['JwtRsaSsaPkcs1PrivateKey'] = _JWTRSASSAPKCS1PRIVATEKEY
DESCRIPTOR.message_types_by_name['JwtRsaSsaPkcs1KeyFormat'] = _JWTRSASSAPKCS1KEYFORMAT
DESCRIPTOR.enum_types_by_name['JwtRsaSsaPkcs1Algorithm'] = _JWTRSASSAPKCS1ALGORITHM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JwtRsaSsaPkcs1PublicKey = _reflection.GeneratedProtocolMessageType('JwtRsaSsaPkcs1PublicKey', (_message.Message,), {

  'CustomKid' : _reflection.GeneratedProtocolMessageType('CustomKid', (_message.Message,), {
    'DESCRIPTOR' : _JWTRSASSAPKCS1PUBLICKEY_CUSTOMKID,
    '__module__' : 'tink.proto.jwt_rsa_ssa_pkcs1_pb2'
    # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtRsaSsaPkcs1PublicKey.CustomKid)
    })
  ,
  'DESCRIPTOR' : _JWTRSASSAPKCS1PUBLICKEY,
  '__module__' : 'tink.proto.jwt_rsa_ssa_pkcs1_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtRsaSsaPkcs1PublicKey)
  })
_sym_db.RegisterMessage(JwtRsaSsaPkcs1PublicKey)
_sym_db.RegisterMessage(JwtRsaSsaPkcs1PublicKey.CustomKid)

JwtRsaSsaPkcs1PrivateKey = _reflection.GeneratedProtocolMessageType('JwtRsaSsaPkcs1PrivateKey', (_message.Message,), {
  'DESCRIPTOR' : _JWTRSASSAPKCS1PRIVATEKEY,
  '__module__' : 'tink.proto.jwt_rsa_ssa_pkcs1_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtRsaSsaPkcs1PrivateKey)
  })
_sym_db.RegisterMessage(JwtRsaSsaPkcs1PrivateKey)

JwtRsaSsaPkcs1KeyFormat = _reflection.GeneratedProtocolMessageType('JwtRsaSsaPkcs1KeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _JWTRSASSAPKCS1KEYFORMAT,
  '__module__' : 'tink.proto.jwt_rsa_ssa_pkcs1_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtRsaSsaPkcs1KeyFormat)
  })
_sym_db.RegisterMessage(JwtRsaSsaPkcs1KeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
