# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/jwt_ecdsa.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/jwt_ecdsa.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z/github.com/google/tink/proto/jwt_ecdsa_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1atink/proto/jwt_ecdsa.proto\x12\x12google.crypto.tink\"\xd5\x01\n\x11JwtEcdsaPublicKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x38\n\talgorithm\x18\x02 \x01(\x0e\x32%.google.crypto.tink.JwtEcdsaAlgorithm\x12\t\n\x01x\x18\x03 \x01(\x0c\x12\t\n\x01y\x18\x04 \x01(\x0c\x12\x43\n\ncustom_kid\x18\x05 \x01(\x0b\x32/.google.crypto.tink.JwtEcdsaPublicKey.CustomKid\x1a\x1a\n\tCustomKid\x12\r\n\x05value\x18\x01 \x01(\t\"s\n\x12JwtEcdsaPrivateKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x39\n\npublic_key\x18\x02 \x01(\x0b\x32%.google.crypto.tink.JwtEcdsaPublicKey\x12\x11\n\tkey_value\x18\x03 \x01(\x0c\"^\n\x11JwtEcdsaKeyFormat\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x38\n\talgorithm\x18\x02 \x01(\x0e\x32%.google.crypto.tink.JwtEcdsaAlgorithm*D\n\x11JwtEcdsaAlgorithm\x12\x0e\n\nES_UNKNOWN\x10\x00\x12\t\n\x05\x45S256\x10\x01\x12\t\n\x05\x45S384\x10\x02\x12\t\n\x05\x45S512\x10\x03\x42Q\n\x1c\x63om.google.crypto.tink.protoP\x01Z/github.com/google/tink/proto/jwt_ecdsa_go_protob\x06proto3'
)

_JWTECDSAALGORITHM = _descriptor.EnumDescriptor(
  name='JwtEcdsaAlgorithm',
  full_name='google.crypto.tink.JwtEcdsaAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ES_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ES256', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ES384', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ES512', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=479,
  serialized_end=547,
)
_sym_db.RegisterEnumDescriptor(_JWTECDSAALGORITHM)

JwtEcdsaAlgorithm = enum_type_wrapper.EnumTypeWrapper(_JWTECDSAALGORITHM)
ES_UNKNOWN = 0
ES256 = 1
ES384 = 2
ES512 = 3



_JWTECDSAPUBLICKEY_CUSTOMKID = _descriptor.Descriptor(
  name='CustomKid',
  full_name='google.crypto.tink.JwtEcdsaPublicKey.CustomKid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='google.crypto.tink.JwtEcdsaPublicKey.CustomKid.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=264,
)

_JWTECDSAPUBLICKEY = _descriptor.Descriptor(
  name='JwtEcdsaPublicKey',
  full_name='google.crypto.tink.JwtEcdsaPublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.JwtEcdsaPublicKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='google.crypto.tink.JwtEcdsaPublicKey.algorithm', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='google.crypto.tink.JwtEcdsaPublicKey.x', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='google.crypto.tink.JwtEcdsaPublicKey.y', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='custom_kid', full_name='google.crypto.tink.JwtEcdsaPublicKey.custom_kid', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_JWTECDSAPUBLICKEY_CUSTOMKID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=264,
)


_JWTECDSAPRIVATEKEY = _descriptor.Descriptor(
  name='JwtEcdsaPrivateKey',
  full_name='google.crypto.tink.JwtEcdsaPrivateKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.JwtEcdsaPrivateKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='google.crypto.tink.JwtEcdsaPrivateKey.public_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.JwtEcdsaPrivateKey.key_value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=381,
)


_JWTECDSAKEYFORMAT = _descriptor.Descriptor(
  name='JwtEcdsaKeyFormat',
  full_name='google.crypto.tink.JwtEcdsaKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.JwtEcdsaKeyFormat.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='google.crypto.tink.JwtEcdsaKeyFormat.algorithm', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=477,
)

_JWTECDSAPUBLICKEY_CUSTOMKID.containing_type = _JWTECDSAPUBLICKEY
_JWTECDSAPUBLICKEY.fields_by_name['algorithm'].enum_type = _JWTECDSAALGORITHM
_JWTECDSAPUBLICKEY.fields_by_name['custom_kid'].message_type = _JWTECDSAPUBLICKEY_CUSTOMKID
_JWTECDSAPRIVATEKEY.fields_by_name['public_key'].message_type = _JWTECDSAPUBLICKEY
_JWTECDSAKEYFORMAT.fields_by_name['algorithm'].enum_type = _JWTECDSAALGORITHM
DESCRIPTOR.message_types_by_name['JwtEcdsaPublicKey'] = _JWTECDSAPUBLICKEY
DESCRIPTOR.message_types_by_name['JwtEcdsaPrivateKey'] = _JWTECDSAPRIVATEKEY
DESCRIPTOR.message_types_by_name['JwtEcdsaKeyFormat'] = _JWTECDSAKEYFORMAT
DESCRIPTOR.enum_types_by_name['JwtEcdsaAlgorithm'] = _JWTECDSAALGORITHM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JwtEcdsaPublicKey = _reflection.GeneratedProtocolMessageType('JwtEcdsaPublicKey', (_message.Message,), {

  'CustomKid' : _reflection.GeneratedProtocolMessageType('CustomKid', (_message.Message,), {
    'DESCRIPTOR' : _JWTECDSAPUBLICKEY_CUSTOMKID,
    '__module__' : 'tink.proto.jwt_ecdsa_pb2'
    # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtEcdsaPublicKey.CustomKid)
    })
  ,
  'DESCRIPTOR' : _JWTECDSAPUBLICKEY,
  '__module__' : 'tink.proto.jwt_ecdsa_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtEcdsaPublicKey)
  })
_sym_db.RegisterMessage(JwtEcdsaPublicKey)
_sym_db.RegisterMessage(JwtEcdsaPublicKey.CustomKid)

JwtEcdsaPrivateKey = _reflection.GeneratedProtocolMessageType('JwtEcdsaPrivateKey', (_message.Message,), {
  'DESCRIPTOR' : _JWTECDSAPRIVATEKEY,
  '__module__' : 'tink.proto.jwt_ecdsa_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtEcdsaPrivateKey)
  })
_sym_db.RegisterMessage(JwtEcdsaPrivateKey)

JwtEcdsaKeyFormat = _reflection.GeneratedProtocolMessageType('JwtEcdsaKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _JWTECDSAKEYFORMAT,
  '__module__' : 'tink.proto.jwt_ecdsa_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtEcdsaKeyFormat)
  })
_sym_db.RegisterMessage(JwtEcdsaKeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
