# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/jwt_rsa_ssa_pss.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/jwt_rsa_ssa_pss.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z5github.com/google/tink/proto/jwt_rsa_ssa_pss_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n tink/proto/jwt_rsa_ssa_pss.proto\x12\x12google.crypto.tink\"\xe1\x01\n\x15JwtRsaSsaPssPublicKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12<\n\talgorithm\x18\x02 \x01(\x0e\x32).google.crypto.tink.JwtRsaSsaPssAlgorithm\x12\t\n\x01n\x18\x03 \x01(\x0c\x12\t\n\x01\x65\x18\x04 \x01(\x0c\x12G\n\ncustom_kid\x18\x05 \x01(\x0b\x32\x33.google.crypto.tink.JwtRsaSsaPssPublicKey.CustomKid\x1a\x1a\n\tCustomKid\x12\r\n\x05value\x18\x01 \x01(\t\"\xae\x01\n\x16JwtRsaSsaPssPrivateKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12=\n\npublic_key\x18\x02 \x01(\x0b\x32).google.crypto.tink.JwtRsaSsaPssPublicKey\x12\t\n\x01\x64\x18\x03 \x01(\x0c\x12\t\n\x01p\x18\x04 \x01(\x0c\x12\t\n\x01q\x18\x05 \x01(\x0c\x12\n\n\x02\x64p\x18\x06 \x01(\x0c\x12\n\n\x02\x64q\x18\x07 \x01(\x0c\x12\x0b\n\x03\x63rt\x18\x08 \x01(\x0c\"\x9d\x01\n\x15JwtRsaSsaPssKeyFormat\x12\x0f\n\x07version\x18\x01 \x01(\r\x12<\n\talgorithm\x18\x02 \x01(\x0e\x32).google.crypto.tink.JwtRsaSsaPssAlgorithm\x12\x1c\n\x14modulus_size_in_bits\x18\x03 \x01(\r\x12\x17\n\x0fpublic_exponent\x18\x04 \x01(\x0c*H\n\x15JwtRsaSsaPssAlgorithm\x12\x0e\n\nPS_UNKNOWN\x10\x00\x12\t\n\x05PS256\x10\x01\x12\t\n\x05PS384\x10\x02\x12\t\n\x05PS512\x10\x03\x42W\n\x1c\x63om.google.crypto.tink.protoP\x01Z5github.com/google/tink/proto/jwt_rsa_ssa_pss_go_protob\x06proto3'
)

_JWTRSASSAPSSALGORITHM = _descriptor.EnumDescriptor(
  name='JwtRsaSsaPssAlgorithm',
  full_name='google.crypto.tink.JwtRsaSsaPssAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PS256', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PS384', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PS512', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=621,
  serialized_end=693,
)
_sym_db.RegisterEnumDescriptor(_JWTRSASSAPSSALGORITHM)

JwtRsaSsaPssAlgorithm = enum_type_wrapper.EnumTypeWrapper(_JWTRSASSAPSSALGORITHM)
PS_UNKNOWN = 0
PS256 = 1
PS384 = 2
PS512 = 3



_JWTRSASSAPSSPUBLICKEY_CUSTOMKID = _descriptor.Descriptor(
  name='CustomKid',
  full_name='google.crypto.tink.JwtRsaSsaPssPublicKey.CustomKid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='google.crypto.tink.JwtRsaSsaPssPublicKey.CustomKid.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=282,
)

_JWTRSASSAPSSPUBLICKEY = _descriptor.Descriptor(
  name='JwtRsaSsaPssPublicKey',
  full_name='google.crypto.tink.JwtRsaSsaPssPublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.JwtRsaSsaPssPublicKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='google.crypto.tink.JwtRsaSsaPssPublicKey.algorithm', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n', full_name='google.crypto.tink.JwtRsaSsaPssPublicKey.n', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='e', full_name='google.crypto.tink.JwtRsaSsaPssPublicKey.e', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='custom_kid', full_name='google.crypto.tink.JwtRsaSsaPssPublicKey.custom_kid', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_JWTRSASSAPSSPUBLICKEY_CUSTOMKID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=282,
)


_JWTRSASSAPSSPRIVATEKEY = _descriptor.Descriptor(
  name='JwtRsaSsaPssPrivateKey',
  full_name='google.crypto.tink.JwtRsaSsaPssPrivateKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.JwtRsaSsaPssPrivateKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='google.crypto.tink.JwtRsaSsaPssPrivateKey.public_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d', full_name='google.crypto.tink.JwtRsaSsaPssPrivateKey.d', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p', full_name='google.crypto.tink.JwtRsaSsaPssPrivateKey.p', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q', full_name='google.crypto.tink.JwtRsaSsaPssPrivateKey.q', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dp', full_name='google.crypto.tink.JwtRsaSsaPssPrivateKey.dp', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dq', full_name='google.crypto.tink.JwtRsaSsaPssPrivateKey.dq', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crt', full_name='google.crypto.tink.JwtRsaSsaPssPrivateKey.crt', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=459,
)


_JWTRSASSAPSSKEYFORMAT = _descriptor.Descriptor(
  name='JwtRsaSsaPssKeyFormat',
  full_name='google.crypto.tink.JwtRsaSsaPssKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.JwtRsaSsaPssKeyFormat.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='google.crypto.tink.JwtRsaSsaPssKeyFormat.algorithm', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='modulus_size_in_bits', full_name='google.crypto.tink.JwtRsaSsaPssKeyFormat.modulus_size_in_bits', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_exponent', full_name='google.crypto.tink.JwtRsaSsaPssKeyFormat.public_exponent', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=619,
)

_JWTRSASSAPSSPUBLICKEY_CUSTOMKID.containing_type = _JWTRSASSAPSSPUBLICKEY
_JWTRSASSAPSSPUBLICKEY.fields_by_name['algorithm'].enum_type = _JWTRSASSAPSSALGORITHM
_JWTRSASSAPSSPUBLICKEY.fields_by_name['custom_kid'].message_type = _JWTRSASSAPSSPUBLICKEY_CUSTOMKID
_JWTRSASSAPSSPRIVATEKEY.fields_by_name['public_key'].message_type = _JWTRSASSAPSSPUBLICKEY
_JWTRSASSAPSSKEYFORMAT.fields_by_name['algorithm'].enum_type = _JWTRSASSAPSSALGORITHM
DESCRIPTOR.message_types_by_name['JwtRsaSsaPssPublicKey'] = _JWTRSASSAPSSPUBLICKEY
DESCRIPTOR.message_types_by_name['JwtRsaSsaPssPrivateKey'] = _JWTRSASSAPSSPRIVATEKEY
DESCRIPTOR.message_types_by_name['JwtRsaSsaPssKeyFormat'] = _JWTRSASSAPSSKEYFORMAT
DESCRIPTOR.enum_types_by_name['JwtRsaSsaPssAlgorithm'] = _JWTRSASSAPSSALGORITHM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JwtRsaSsaPssPublicKey = _reflection.GeneratedProtocolMessageType('JwtRsaSsaPssPublicKey', (_message.Message,), {

  'CustomKid' : _reflection.GeneratedProtocolMessageType('CustomKid', (_message.Message,), {
    'DESCRIPTOR' : _JWTRSASSAPSSPUBLICKEY_CUSTOMKID,
    '__module__' : 'tink.proto.jwt_rsa_ssa_pss_pb2'
    # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtRsaSsaPssPublicKey.CustomKid)
    })
  ,
  'DESCRIPTOR' : _JWTRSASSAPSSPUBLICKEY,
  '__module__' : 'tink.proto.jwt_rsa_ssa_pss_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtRsaSsaPssPublicKey)
  })
_sym_db.RegisterMessage(JwtRsaSsaPssPublicKey)
_sym_db.RegisterMessage(JwtRsaSsaPssPublicKey.CustomKid)

JwtRsaSsaPssPrivateKey = _reflection.GeneratedProtocolMessageType('JwtRsaSsaPssPrivateKey', (_message.Message,), {
  'DESCRIPTOR' : _JWTRSASSAPSSPRIVATEKEY,
  '__module__' : 'tink.proto.jwt_rsa_ssa_pss_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtRsaSsaPssPrivateKey)
  })
_sym_db.RegisterMessage(JwtRsaSsaPssPrivateKey)

JwtRsaSsaPssKeyFormat = _reflection.GeneratedProtocolMessageType('JwtRsaSsaPssKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _JWTRSASSAPSSKEYFORMAT,
  '__module__' : 'tink.proto.jwt_rsa_ssa_pss_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtRsaSsaPssKeyFormat)
  })
_sym_db.RegisterMessage(JwtRsaSsaPssKeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
