# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/jwt_hmac.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/jwt_hmac.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z.github.com/google/tink/proto/jwt_hmac_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19tink/proto/jwt_hmac.proto\x12\x12google.crypto.tink\"\xc3\x01\n\nJwtHmacKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x37\n\talgorithm\x18\x02 \x01(\x0e\x32$.google.crypto.tink.JwtHmacAlgorithm\x12\x11\n\tkey_value\x18\x03 \x01(\x0c\x12<\n\ncustom_kid\x18\x04 \x01(\x0b\x32(.google.crypto.tink.JwtHmacKey.CustomKid\x1a\x1a\n\tCustomKid\x12\r\n\x05value\x18\x01 \x01(\t\"n\n\x10JwtHmacKeyFormat\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x37\n\talgorithm\x18\x02 \x01(\x0e\x32$.google.crypto.tink.JwtHmacAlgorithm\x12\x10\n\x08key_size\x18\x03 \x01(\r*C\n\x10JwtHmacAlgorithm\x12\x0e\n\nHS_UNKNOWN\x10\x00\x12\t\n\x05HS256\x10\x01\x12\t\n\x05HS384\x10\x02\x12\t\n\x05HS512\x10\x03\x42P\n\x1c\x63om.google.crypto.tink.protoP\x01Z.github.com/google/tink/proto/jwt_hmac_go_protob\x06proto3'
)

_JWTHMACALGORITHM = _descriptor.EnumDescriptor(
  name='JwtHmacAlgorithm',
  full_name='google.crypto.tink.JwtHmacAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HS256', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HS384', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HS512', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=359,
  serialized_end=426,
)
_sym_db.RegisterEnumDescriptor(_JWTHMACALGORITHM)

JwtHmacAlgorithm = enum_type_wrapper.EnumTypeWrapper(_JWTHMACALGORITHM)
HS_UNKNOWN = 0
HS256 = 1
HS384 = 2
HS512 = 3



_JWTHMACKEY_CUSTOMKID = _descriptor.Descriptor(
  name='CustomKid',
  full_name='google.crypto.tink.JwtHmacKey.CustomKid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='google.crypto.tink.JwtHmacKey.CustomKid.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=245,
)

_JWTHMACKEY = _descriptor.Descriptor(
  name='JwtHmacKey',
  full_name='google.crypto.tink.JwtHmacKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.JwtHmacKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='google.crypto.tink.JwtHmacKey.algorithm', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='google.crypto.tink.JwtHmacKey.key_value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='custom_kid', full_name='google.crypto.tink.JwtHmacKey.custom_kid', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_JWTHMACKEY_CUSTOMKID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=245,
)


_JWTHMACKEYFORMAT = _descriptor.Descriptor(
  name='JwtHmacKeyFormat',
  full_name='google.crypto.tink.JwtHmacKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.JwtHmacKeyFormat.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='google.crypto.tink.JwtHmacKeyFormat.algorithm', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key_size', full_name='google.crypto.tink.JwtHmacKeyFormat.key_size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=357,
)

_JWTHMACKEY_CUSTOMKID.containing_type = _JWTHMACKEY
_JWTHMACKEY.fields_by_name['algorithm'].enum_type = _JWTHMACALGORITHM
_JWTHMACKEY.fields_by_name['custom_kid'].message_type = _JWTHMACKEY_CUSTOMKID
_JWTHMACKEYFORMAT.fields_by_name['algorithm'].enum_type = _JWTHMACALGORITHM
DESCRIPTOR.message_types_by_name['JwtHmacKey'] = _JWTHMACKEY
DESCRIPTOR.message_types_by_name['JwtHmacKeyFormat'] = _JWTHMACKEYFORMAT
DESCRIPTOR.enum_types_by_name['JwtHmacAlgorithm'] = _JWTHMACALGORITHM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JwtHmacKey = _reflection.GeneratedProtocolMessageType('JwtHmacKey', (_message.Message,), {

  'CustomKid' : _reflection.GeneratedProtocolMessageType('CustomKid', (_message.Message,), {
    'DESCRIPTOR' : _JWTHMACKEY_CUSTOMKID,
    '__module__' : 'tink.proto.jwt_hmac_pb2'
    # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtHmacKey.CustomKid)
    })
  ,
  'DESCRIPTOR' : _JWTHMACKEY,
  '__module__' : 'tink.proto.jwt_hmac_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtHmacKey)
  })
_sym_db.RegisterMessage(JwtHmacKey)
_sym_db.RegisterMessage(JwtHmacKey.CustomKid)

JwtHmacKeyFormat = _reflection.GeneratedProtocolMessageType('JwtHmacKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _JWTHMACKEYFORMAT,
  '__module__' : 'tink.proto.jwt_hmac_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.JwtHmacKeyFormat)
  })
_sym_db.RegisterMessage(JwtHmacKeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
