# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/kms_envelope.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import tink_pb2 as tink_dot_proto_dot_tink__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/kms_envelope.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z2github.com/google/tink/proto/kms_envelope_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dtink/proto/kms_envelope.proto\x12\x12google.crypto.tink\x1a\x15tink/proto/tink.proto\"b\n\x18KmsEnvelopeAeadKeyFormat\x12\x0f\n\x07kek_uri\x18\x01 \x01(\t\x12\x35\n\x0c\x64\x65k_template\x18\x02 \x01(\x0b\x32\x1f.google.crypto.tink.KeyTemplate\"c\n\x12KmsEnvelopeAeadKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12<\n\x06params\x18\x02 \x01(\x0b\x32,.google.crypto.tink.KmsEnvelopeAeadKeyFormatBT\n\x1c\x63om.google.crypto.tink.protoP\x01Z2github.com/google/tink/proto/kms_envelope_go_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_tink__pb2.DESCRIPTOR,])




_KMSENVELOPEAEADKEYFORMAT = _descriptor.Descriptor(
  name='KmsEnvelopeAeadKeyFormat',
  full_name='google.crypto.tink.KmsEnvelopeAeadKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kek_uri', full_name='google.crypto.tink.KmsEnvelopeAeadKeyFormat.kek_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dek_template', full_name='google.crypto.tink.KmsEnvelopeAeadKeyFormat.dek_template', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=174,
)


_KMSENVELOPEAEADKEY = _descriptor.Descriptor(
  name='KmsEnvelopeAeadKey',
  full_name='google.crypto.tink.KmsEnvelopeAeadKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.KmsEnvelopeAeadKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.KmsEnvelopeAeadKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=275,
)

_KMSENVELOPEAEADKEYFORMAT.fields_by_name['dek_template'].message_type = tink_dot_proto_dot_tink__pb2._KEYTEMPLATE
_KMSENVELOPEAEADKEY.fields_by_name['params'].message_type = _KMSENVELOPEAEADKEYFORMAT
DESCRIPTOR.message_types_by_name['KmsEnvelopeAeadKeyFormat'] = _KMSENVELOPEAEADKEYFORMAT
DESCRIPTOR.message_types_by_name['KmsEnvelopeAeadKey'] = _KMSENVELOPEAEADKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KmsEnvelopeAeadKeyFormat = _reflection.GeneratedProtocolMessageType('KmsEnvelopeAeadKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _KMSENVELOPEAEADKEYFORMAT,
  '__module__' : 'tink.proto.kms_envelope_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.KmsEnvelopeAeadKeyFormat)
  })
_sym_db.RegisterMessage(KmsEnvelopeAeadKeyFormat)

KmsEnvelopeAeadKey = _reflection.GeneratedProtocolMessageType('KmsEnvelopeAeadKey', (_message.Message,), {
  'DESCRIPTOR' : _KMSENVELOPEAEADKEY,
  '__module__' : 'tink.proto.kms_envelope_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.KmsEnvelopeAeadKey)
  })
_sym_db.RegisterMessage(KmsEnvelopeAeadKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
