# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/kms_aead.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/kms_aead.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z.github.com/google/tink/proto/kms_aead_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19tink/proto/kms_aead.proto\x12\x12google.crypto.tink\"#\n\x10KmsAeadKeyFormat\x12\x0f\n\x07key_uri\x18\x01 \x01(\t\"S\n\nKmsAeadKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x34\n\x06params\x18\x02 \x01(\x0b\x32$.google.crypto.tink.KmsAeadKeyFormatBP\n\x1c\x63om.google.crypto.tink.protoP\x01Z.github.com/google/tink/proto/kms_aead_go_protob\x06proto3'
)




_KMSAEADKEYFORMAT = _descriptor.Descriptor(
  name='KmsAeadKeyFormat',
  full_name='google.crypto.tink.KmsAeadKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_uri', full_name='google.crypto.tink.KmsAeadKeyFormat.key_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=84,
)


_KMSAEADKEY = _descriptor.Descriptor(
  name='KmsAeadKey',
  full_name='google.crypto.tink.KmsAeadKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.KmsAeadKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.KmsAeadKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=169,
)

_KMSAEADKEY.fields_by_name['params'].message_type = _KMSAEADKEYFORMAT
DESCRIPTOR.message_types_by_name['KmsAeadKeyFormat'] = _KMSAEADKEYFORMAT
DESCRIPTOR.message_types_by_name['KmsAeadKey'] = _KMSAEADKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KmsAeadKeyFormat = _reflection.GeneratedProtocolMessageType('KmsAeadKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _KMSAEADKEYFORMAT,
  '__module__' : 'tink.proto.kms_aead_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.KmsAeadKeyFormat)
  })
_sym_db.RegisterMessage(KmsAeadKeyFormat)

KmsAeadKey = _reflection.GeneratedProtocolMessageType('KmsAeadKey', (_message.Message,), {
  'DESCRIPTOR' : _KMSAEADKEY,
  '__module__' : 'tink.proto.kms_aead_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.KmsAeadKey)
  })
_sym_db.RegisterMessage(KmsAeadKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
