# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/prf_based_deriver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import tink_pb2 as tink_dot_proto_dot_tink__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/prf_based_deriver.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z7github.com/google/tink/proto/prf_based_deriver_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"tink/proto/prf_based_deriver.proto\x12\x12google.crypto.tink\x1a\x15tink/proto/tink.proto\"V\n\x15PrfBasedDeriverParams\x12=\n\x14\x64\x65rived_key_template\x18\x01 \x01(\x0b\x32\x1f.google.crypto.tink.KeyTemplate\"\x90\x01\n\x18PrfBasedDeriverKeyFormat\x12\x39\n\x10prf_key_template\x18\x01 \x01(\x0b\x32\x1f.google.crypto.tink.KeyTemplate\x12\x39\n\x06params\x18\x02 \x01(\x0b\x32).google.crypto.tink.PrfBasedDeriverParams\"\x8e\x01\n\x12PrfBasedDeriverKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12,\n\x07prf_key\x18\x02 \x01(\x0b\x32\x1b.google.crypto.tink.KeyData\x12\x39\n\x06params\x18\x03 \x01(\x0b\x32).google.crypto.tink.PrfBasedDeriverParamsBY\n\x1c\x63om.google.crypto.tink.protoP\x01Z7github.com/google/tink/proto/prf_based_deriver_go_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_tink__pb2.DESCRIPTOR,])




_PRFBASEDDERIVERPARAMS = _descriptor.Descriptor(
  name='PrfBasedDeriverParams',
  full_name='google.crypto.tink.PrfBasedDeriverParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='derived_key_template', full_name='google.crypto.tink.PrfBasedDeriverParams.derived_key_template', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=167,
)


_PRFBASEDDERIVERKEYFORMAT = _descriptor.Descriptor(
  name='PrfBasedDeriverKeyFormat',
  full_name='google.crypto.tink.PrfBasedDeriverKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prf_key_template', full_name='google.crypto.tink.PrfBasedDeriverKeyFormat.prf_key_template', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.PrfBasedDeriverKeyFormat.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=314,
)


_PRFBASEDDERIVERKEY = _descriptor.Descriptor(
  name='PrfBasedDeriverKey',
  full_name='google.crypto.tink.PrfBasedDeriverKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.PrfBasedDeriverKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prf_key', full_name='google.crypto.tink.PrfBasedDeriverKey.prf_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.PrfBasedDeriverKey.params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=459,
)

_PRFBASEDDERIVERPARAMS.fields_by_name['derived_key_template'].message_type = tink_dot_proto_dot_tink__pb2._KEYTEMPLATE
_PRFBASEDDERIVERKEYFORMAT.fields_by_name['prf_key_template'].message_type = tink_dot_proto_dot_tink__pb2._KEYTEMPLATE
_PRFBASEDDERIVERKEYFORMAT.fields_by_name['params'].message_type = _PRFBASEDDERIVERPARAMS
_PRFBASEDDERIVERKEY.fields_by_name['prf_key'].message_type = tink_dot_proto_dot_tink__pb2._KEYDATA
_PRFBASEDDERIVERKEY.fields_by_name['params'].message_type = _PRFBASEDDERIVERPARAMS
DESCRIPTOR.message_types_by_name['PrfBasedDeriverParams'] = _PRFBASEDDERIVERPARAMS
DESCRIPTOR.message_types_by_name['PrfBasedDeriverKeyFormat'] = _PRFBASEDDERIVERKEYFORMAT
DESCRIPTOR.message_types_by_name['PrfBasedDeriverKey'] = _PRFBASEDDERIVERKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrfBasedDeriverParams = _reflection.GeneratedProtocolMessageType('PrfBasedDeriverParams', (_message.Message,), {
  'DESCRIPTOR' : _PRFBASEDDERIVERPARAMS,
  '__module__' : 'tink.proto.prf_based_deriver_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.PrfBasedDeriverParams)
  })
_sym_db.RegisterMessage(PrfBasedDeriverParams)

PrfBasedDeriverKeyFormat = _reflection.GeneratedProtocolMessageType('PrfBasedDeriverKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _PRFBASEDDERIVERKEYFORMAT,
  '__module__' : 'tink.proto.prf_based_deriver_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.PrfBasedDeriverKeyFormat)
  })
_sym_db.RegisterMessage(PrfBasedDeriverKeyFormat)

PrfBasedDeriverKey = _reflection.GeneratedProtocolMessageType('PrfBasedDeriverKey', (_message.Message,), {
  'DESCRIPTOR' : _PRFBASEDDERIVERKEY,
  '__module__' : 'tink.proto.prf_based_deriver_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.PrfBasedDeriverKey)
  })
_sym_db.RegisterMessage(PrfBasedDeriverKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
