# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/rsa_ssa_pkcs1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import common_pb2 as tink_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/rsa_ssa_pkcs1.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z3github.com/google/tink/proto/rsa_ssa_pkcs1_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1etink/proto/rsa_ssa_pkcs1.proto\x12\x12google.crypto.tink\x1a\x17tink/proto/common.proto\"D\n\x11RsaSsaPkcs1Params\x12/\n\thash_type\x18\x01 \x01(\x0e\x32\x1c.google.crypto.tink.HashType\"t\n\x14RsaSsaPkcs1PublicKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x35\n\x06params\x18\x02 \x01(\x0b\x32%.google.crypto.tink.RsaSsaPkcs1Params\x12\t\n\x01n\x18\x03 \x01(\x0c\x12\t\n\x01\x65\x18\x04 \x01(\x0c\"\xac\x01\n\x15RsaSsaPkcs1PrivateKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12<\n\npublic_key\x18\x02 \x01(\x0b\x32(.google.crypto.tink.RsaSsaPkcs1PublicKey\x12\t\n\x01\x64\x18\x03 \x01(\x0c\x12\t\n\x01p\x18\x04 \x01(\x0c\x12\t\n\x01q\x18\x05 \x01(\x0c\x12\n\n\x02\x64p\x18\x06 \x01(\x0c\x12\n\n\x02\x64q\x18\x07 \x01(\x0c\x12\x0b\n\x03\x63rt\x18\x08 \x01(\x0c\"\x84\x01\n\x14RsaSsaPkcs1KeyFormat\x12\x35\n\x06params\x18\x01 \x01(\x0b\x32%.google.crypto.tink.RsaSsaPkcs1Params\x12\x1c\n\x14modulus_size_in_bits\x18\x02 \x01(\r\x12\x17\n\x0fpublic_exponent\x18\x03 \x01(\x0c\x42U\n\x1c\x63om.google.crypto.tink.protoP\x01Z3github.com/google/tink/proto/rsa_ssa_pkcs1_go_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_common__pb2.DESCRIPTOR,])




_RSASSAPKCS1PARAMS = _descriptor.Descriptor(
  name='RsaSsaPkcs1Params',
  full_name='google.crypto.tink.RsaSsaPkcs1Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash_type', full_name='google.crypto.tink.RsaSsaPkcs1Params.hash_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=147,
)


_RSASSAPKCS1PUBLICKEY = _descriptor.Descriptor(
  name='RsaSsaPkcs1PublicKey',
  full_name='google.crypto.tink.RsaSsaPkcs1PublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.RsaSsaPkcs1PublicKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.RsaSsaPkcs1PublicKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n', full_name='google.crypto.tink.RsaSsaPkcs1PublicKey.n', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='e', full_name='google.crypto.tink.RsaSsaPkcs1PublicKey.e', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=265,
)


_RSASSAPKCS1PRIVATEKEY = _descriptor.Descriptor(
  name='RsaSsaPkcs1PrivateKey',
  full_name='google.crypto.tink.RsaSsaPkcs1PrivateKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.RsaSsaPkcs1PrivateKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='google.crypto.tink.RsaSsaPkcs1PrivateKey.public_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d', full_name='google.crypto.tink.RsaSsaPkcs1PrivateKey.d', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p', full_name='google.crypto.tink.RsaSsaPkcs1PrivateKey.p', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q', full_name='google.crypto.tink.RsaSsaPkcs1PrivateKey.q', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dp', full_name='google.crypto.tink.RsaSsaPkcs1PrivateKey.dp', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dq', full_name='google.crypto.tink.RsaSsaPkcs1PrivateKey.dq', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crt', full_name='google.crypto.tink.RsaSsaPkcs1PrivateKey.crt', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=440,
)


_RSASSAPKCS1KEYFORMAT = _descriptor.Descriptor(
  name='RsaSsaPkcs1KeyFormat',
  full_name='google.crypto.tink.RsaSsaPkcs1KeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.RsaSsaPkcs1KeyFormat.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='modulus_size_in_bits', full_name='google.crypto.tink.RsaSsaPkcs1KeyFormat.modulus_size_in_bits', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_exponent', full_name='google.crypto.tink.RsaSsaPkcs1KeyFormat.public_exponent', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=575,
)

_RSASSAPKCS1PARAMS.fields_by_name['hash_type'].enum_type = tink_dot_proto_dot_common__pb2._HASHTYPE
_RSASSAPKCS1PUBLICKEY.fields_by_name['params'].message_type = _RSASSAPKCS1PARAMS
_RSASSAPKCS1PRIVATEKEY.fields_by_name['public_key'].message_type = _RSASSAPKCS1PUBLICKEY
_RSASSAPKCS1KEYFORMAT.fields_by_name['params'].message_type = _RSASSAPKCS1PARAMS
DESCRIPTOR.message_types_by_name['RsaSsaPkcs1Params'] = _RSASSAPKCS1PARAMS
DESCRIPTOR.message_types_by_name['RsaSsaPkcs1PublicKey'] = _RSASSAPKCS1PUBLICKEY
DESCRIPTOR.message_types_by_name['RsaSsaPkcs1PrivateKey'] = _RSASSAPKCS1PRIVATEKEY
DESCRIPTOR.message_types_by_name['RsaSsaPkcs1KeyFormat'] = _RSASSAPKCS1KEYFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RsaSsaPkcs1Params = _reflection.GeneratedProtocolMessageType('RsaSsaPkcs1Params', (_message.Message,), {
  'DESCRIPTOR' : _RSASSAPKCS1PARAMS,
  '__module__' : 'tink.proto.rsa_ssa_pkcs1_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.RsaSsaPkcs1Params)
  })
_sym_db.RegisterMessage(RsaSsaPkcs1Params)

RsaSsaPkcs1PublicKey = _reflection.GeneratedProtocolMessageType('RsaSsaPkcs1PublicKey', (_message.Message,), {
  'DESCRIPTOR' : _RSASSAPKCS1PUBLICKEY,
  '__module__' : 'tink.proto.rsa_ssa_pkcs1_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.RsaSsaPkcs1PublicKey)
  })
_sym_db.RegisterMessage(RsaSsaPkcs1PublicKey)

RsaSsaPkcs1PrivateKey = _reflection.GeneratedProtocolMessageType('RsaSsaPkcs1PrivateKey', (_message.Message,), {
  'DESCRIPTOR' : _RSASSAPKCS1PRIVATEKEY,
  '__module__' : 'tink.proto.rsa_ssa_pkcs1_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.RsaSsaPkcs1PrivateKey)
  })
_sym_db.RegisterMessage(RsaSsaPkcs1PrivateKey)

RsaSsaPkcs1KeyFormat = _reflection.GeneratedProtocolMessageType('RsaSsaPkcs1KeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _RSASSAPKCS1KEYFORMAT,
  '__module__' : 'tink.proto.rsa_ssa_pkcs1_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.RsaSsaPkcs1KeyFormat)
  })
_sym_db.RegisterMessage(RsaSsaPkcs1KeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
