# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/rsa_ssa_pss.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import common_pb2 as tink_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/rsa_ssa_pss.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=b'\n\034com.google.crypto.tink.protoP\001Z1github.com/google/tink/proto/rsa_ssa_pss_go_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ctink/proto/rsa_ssa_pss.proto\x12\x12google.crypto.tink\x1a\x17tink/proto/common.proto\"\x87\x01\n\x0fRsaSsaPssParams\x12.\n\x08sig_hash\x18\x01 \x01(\x0e\x32\x1c.google.crypto.tink.HashType\x12/\n\tmgf1_hash\x18\x02 \x01(\x0e\x32\x1c.google.crypto.tink.HashType\x12\x13\n\x0bsalt_length\x18\x03 \x01(\x05\"p\n\x12RsaSsaPssPublicKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x33\n\x06params\x18\x02 \x01(\x0b\x32#.google.crypto.tink.RsaSsaPssParams\x12\t\n\x01n\x18\x03 \x01(\x0c\x12\t\n\x01\x65\x18\x04 \x01(\x0c\"\xa8\x01\n\x13RsaSsaPssPrivateKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12:\n\npublic_key\x18\x02 \x01(\x0b\x32&.google.crypto.tink.RsaSsaPssPublicKey\x12\t\n\x01\x64\x18\x03 \x01(\x0c\x12\t\n\x01p\x18\x04 \x01(\x0c\x12\t\n\x01q\x18\x05 \x01(\x0c\x12\n\n\x02\x64p\x18\x06 \x01(\x0c\x12\n\n\x02\x64q\x18\x07 \x01(\x0c\x12\x0b\n\x03\x63rt\x18\x08 \x01(\x0c\"\x80\x01\n\x12RsaSsaPssKeyFormat\x12\x33\n\x06params\x18\x01 \x01(\x0b\x32#.google.crypto.tink.RsaSsaPssParams\x12\x1c\n\x14modulus_size_in_bits\x18\x02 \x01(\r\x12\x17\n\x0fpublic_exponent\x18\x03 \x01(\x0c\x42S\n\x1c\x63om.google.crypto.tink.protoP\x01Z1github.com/google/tink/proto/rsa_ssa_pss_go_protob\x06proto3'
  ,
  dependencies=[tink_dot_proto_dot_common__pb2.DESCRIPTOR,])




_RSASSAPSSPARAMS = _descriptor.Descriptor(
  name='RsaSsaPssParams',
  full_name='google.crypto.tink.RsaSsaPssParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sig_hash', full_name='google.crypto.tink.RsaSsaPssParams.sig_hash', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mgf1_hash', full_name='google.crypto.tink.RsaSsaPssParams.mgf1_hash', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='salt_length', full_name='google.crypto.tink.RsaSsaPssParams.salt_length', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=213,
)


_RSASSAPSSPUBLICKEY = _descriptor.Descriptor(
  name='RsaSsaPssPublicKey',
  full_name='google.crypto.tink.RsaSsaPssPublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.RsaSsaPssPublicKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.RsaSsaPssPublicKey.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n', full_name='google.crypto.tink.RsaSsaPssPublicKey.n', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='e', full_name='google.crypto.tink.RsaSsaPssPublicKey.e', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=327,
)


_RSASSAPSSPRIVATEKEY = _descriptor.Descriptor(
  name='RsaSsaPssPrivateKey',
  full_name='google.crypto.tink.RsaSsaPssPrivateKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.crypto.tink.RsaSsaPssPrivateKey.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='google.crypto.tink.RsaSsaPssPrivateKey.public_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d', full_name='google.crypto.tink.RsaSsaPssPrivateKey.d', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p', full_name='google.crypto.tink.RsaSsaPssPrivateKey.p', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q', full_name='google.crypto.tink.RsaSsaPssPrivateKey.q', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dp', full_name='google.crypto.tink.RsaSsaPssPrivateKey.dp', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dq', full_name='google.crypto.tink.RsaSsaPssPrivateKey.dq', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crt', full_name='google.crypto.tink.RsaSsaPssPrivateKey.crt', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=498,
)


_RSASSAPSSKEYFORMAT = _descriptor.Descriptor(
  name='RsaSsaPssKeyFormat',
  full_name='google.crypto.tink.RsaSsaPssKeyFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='google.crypto.tink.RsaSsaPssKeyFormat.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='modulus_size_in_bits', full_name='google.crypto.tink.RsaSsaPssKeyFormat.modulus_size_in_bits', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_exponent', full_name='google.crypto.tink.RsaSsaPssKeyFormat.public_exponent', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=629,
)

_RSASSAPSSPARAMS.fields_by_name['sig_hash'].enum_type = tink_dot_proto_dot_common__pb2._HASHTYPE
_RSASSAPSSPARAMS.fields_by_name['mgf1_hash'].enum_type = tink_dot_proto_dot_common__pb2._HASHTYPE
_RSASSAPSSPUBLICKEY.fields_by_name['params'].message_type = _RSASSAPSSPARAMS
_RSASSAPSSPRIVATEKEY.fields_by_name['public_key'].message_type = _RSASSAPSSPUBLICKEY
_RSASSAPSSKEYFORMAT.fields_by_name['params'].message_type = _RSASSAPSSPARAMS
DESCRIPTOR.message_types_by_name['RsaSsaPssParams'] = _RSASSAPSSPARAMS
DESCRIPTOR.message_types_by_name['RsaSsaPssPublicKey'] = _RSASSAPSSPUBLICKEY
DESCRIPTOR.message_types_by_name['RsaSsaPssPrivateKey'] = _RSASSAPSSPRIVATEKEY
DESCRIPTOR.message_types_by_name['RsaSsaPssKeyFormat'] = _RSASSAPSSKEYFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RsaSsaPssParams = _reflection.GeneratedProtocolMessageType('RsaSsaPssParams', (_message.Message,), {
  'DESCRIPTOR' : _RSASSAPSSPARAMS,
  '__module__' : 'tink.proto.rsa_ssa_pss_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.RsaSsaPssParams)
  })
_sym_db.RegisterMessage(RsaSsaPssParams)

RsaSsaPssPublicKey = _reflection.GeneratedProtocolMessageType('RsaSsaPssPublicKey', (_message.Message,), {
  'DESCRIPTOR' : _RSASSAPSSPUBLICKEY,
  '__module__' : 'tink.proto.rsa_ssa_pss_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.RsaSsaPssPublicKey)
  })
_sym_db.RegisterMessage(RsaSsaPssPublicKey)

RsaSsaPssPrivateKey = _reflection.GeneratedProtocolMessageType('RsaSsaPssPrivateKey', (_message.Message,), {
  'DESCRIPTOR' : _RSASSAPSSPRIVATEKEY,
  '__module__' : 'tink.proto.rsa_ssa_pss_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.RsaSsaPssPrivateKey)
  })
_sym_db.RegisterMessage(RsaSsaPssPrivateKey)

RsaSsaPssKeyFormat = _reflection.GeneratedProtocolMessageType('RsaSsaPssKeyFormat', (_message.Message,), {
  'DESCRIPTOR' : _RSASSAPSSKEYFORMAT,
  '__module__' : 'tink.proto.rsa_ssa_pss_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.RsaSsaPssKeyFormat)
  })
_sym_db.RegisterMessage(RsaSsaPssKeyFormat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
