# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tink/proto/test_proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tink/proto/test_proto.proto',
  package='google.crypto.tink',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1btink/proto/test_proto.proto\x12\x12google.crypto.tink\"%\n\tTestProto\x12\x0b\n\x03num\x18\x01 \x01(\x04\x12\x0b\n\x03str\x18\x02 \x01(\x0c\"\x7f\n\x0fNestedTestProto\x12(\n\x01\x61\x18\x01 \x01(\x0b\x32\x1d.google.crypto.tink.TestProto\x12(\n\x01\x62\x18\x02 \x01(\x0b\x32\x1d.google.crypto.tink.TestProto\x12\x0b\n\x03num\x18\x03 \x01(\x04\x12\x0b\n\x03str\x18\x04 \x01(\x0c\x62\x06proto3'
)




_TESTPROTO = _descriptor.Descriptor(
  name='TestProto',
  full_name='google.crypto.tink.TestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='google.crypto.tink.TestProto.num', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='str', full_name='google.crypto.tink.TestProto.str', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=88,
)


_NESTEDTESTPROTO = _descriptor.Descriptor(
  name='NestedTestProto',
  full_name='google.crypto.tink.NestedTestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='google.crypto.tink.NestedTestProto.a', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='google.crypto.tink.NestedTestProto.b', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num', full_name='google.crypto.tink.NestedTestProto.num', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='str', full_name='google.crypto.tink.NestedTestProto.str', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=217,
)

_NESTEDTESTPROTO.fields_by_name['a'].message_type = _TESTPROTO
_NESTEDTESTPROTO.fields_by_name['b'].message_type = _TESTPROTO
DESCRIPTOR.message_types_by_name['TestProto'] = _TESTPROTO
DESCRIPTOR.message_types_by_name['NestedTestProto'] = _NESTEDTESTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestProto = _reflection.GeneratedProtocolMessageType('TestProto', (_message.Message,), {
  'DESCRIPTOR' : _TESTPROTO,
  '__module__' : 'tink.proto.test_proto_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.TestProto)
  })
_sym_db.RegisterMessage(TestProto)

NestedTestProto = _reflection.GeneratedProtocolMessageType('NestedTestProto', (_message.Message,), {
  'DESCRIPTOR' : _NESTEDTESTPROTO,
  '__module__' : 'tink.proto.test_proto_pb2'
  # @@protoc_insertion_point(class_scope:google.crypto.tink.NestedTestProto)
  })
_sym_db.RegisterMessage(NestedTestProto)


# @@protoc_insertion_point(module_scope)
